#!/usr/bin/env python3
"""Generate DOCX briefing for Velox (veloxaban) — Oral Factor XIa inhibitor for stroke prevention in AF.

Loads images from local images/velox/ directory (generated by generate-images.sh).
Includes CDN URLs as captions for each image.
"""

import os
import sys
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml

# --- Configuration ---
SITE_NAME = "velox"
BRAND_COLOUR = RGBColor(0x1A, 0x36, 0x5D)   # Deep Navy
ACCENT_COLOUR = RGBColor(0xC6, 0x28, 0x28)   # Crimson Red
GOLD = RGBColor(0xEF, 0xAB, 0x00)            # Warm Gold
AZ_MAGENTA = RGBColor(0x83, 0x00, 0x51)
DARK_TEXT = RGBColor(0x36, 0x3B, 0x3B)
GREY_TEXT = RGBColor(0x66, 0x66, 0x66)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
RED_NOTICE = RGBColor(0xCC, 0x00, 0x00)

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG_DIR = os.path.join(PROJECT_DIR, "images", SITE_NAME)
CDN_BASE = f"https://{SITE_NAME}-images.pages.dev"
OUTPUT_PATH = os.path.join(PROJECT_DIR, "sites", SITE_NAME, "Velox-Website-Briefing.docx")

# --- Image manifest (filename → usage context) ---
IMAGE_MANIFEST = {
    "hero-home.jpeg": "Home — hero",
    "hero-efficacy.jpeg": "VELOCITY Data — hero",
    "hero-moa.jpeg": "How VELOX Works — hero",
    "card-stroke.jpeg": "Home — stroke reduction card",
    "card-bleeding.jpeg": "Home — bleeding safety card",
    "card-dosing.jpeg": "Home — dosing simplicity card",
    "columns-moa-preview.jpeg": "Home — MoA teaser",
    "tab-velocity-af.jpeg": "VELOCITY Data — AF stroke tab",
    "tab-velocity-bleed.jpeg": "VELOCITY Data — bleeding safety tab",
    "card-bleeding-events.jpeg": "Safety — bleeding events card",
    "card-hepatic.jpeg": "Safety — hepatic monitoring card",
    "card-gi-events.jpeg": "Safety — GI events card",
    "columns-dosing.jpeg": "Dosing — once-daily regimen",
    "columns-monitoring.jpeg": "Dosing — monitoring",
    "card-prescribing.jpeg": "Resources — prescribing guide card",
}


# --- Document helpers ---

def set_cell_shading(cell, color_hex):
    shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>')
    cell._tc.get_or_add_tcPr().append(shading)


def add_heading(doc, text, level=1, color=None):
    h = doc.add_heading(text, level=level)
    if color:
        for run in h.runs:
            run.font.color.rgb = color
    return h


def add_body(doc, text, bold=False, italic=False, size=Pt(10)):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = size
    run.font.color.rgb = DARK_TEXT
    run.bold = bold
    run.italic = italic
    return p


def add_image_with_caption(doc, filename, width=Inches(4.5)):
    """Add image from local file with CDN URL caption."""
    local_path = os.path.join(IMG_DIR, filename)
    cdn_url = f"{CDN_BASE}/{filename}"
    usage = IMAGE_MANIFEST.get(filename, "")

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    if os.path.isfile(local_path) and os.path.getsize(local_path) > 1000:
        run = p.add_run()
        try:
            run.add_picture(local_path, width=width)
            print(f"  [OK] {filename}")
        except Exception as e:
            run = p.add_run(f"[Image: {filename} — file exists but embed failed: {e}]")
            run.font.color.rgb = GREY_TEXT
            run.font.size = Pt(9)
            run.italic = True
    else:
        run = p.add_run(f"[Image: {filename} — not yet generated]")
        run.font.color.rgb = GREY_TEXT
        run.font.size = Pt(9)
        run.italic = True
        print(f"  [SKIP] {filename} — not found at {local_path}")

    # CDN URL caption
    cap = doc.add_paragraph()
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = cap.add_run(cdn_url)
    r.font.size = Pt(8)
    r.font.color.rgb = RGBColor(0x00, 0x55, 0x99)
    r.underline = True

    # Usage context
    if usage:
        usage_p = doc.add_paragraph()
        usage_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r2 = usage_p.add_run(f"Usage: {usage}")
        r2.font.size = Pt(8)
        r2.font.color.rgb = GREY_TEXT
        r2.italic = True

    return p


def add_table(doc, headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = 'Table Grid'

    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = ""
        p = cell.paragraphs[0]
        run = p.add_run(h)
        run.bold = True
        run.font.size = Pt(9)
        run.font.color.rgb = WHITE
        set_cell_shading(cell, "830051")

    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = ""
            p = cell.paragraphs[0]
            run = p.add_run(str(val))
            run.font.size = Pt(9)
            run.font.color.rgb = DARK_TEXT
            if r_idx % 2 == 1:
                set_cell_shading(cell, "F8F8F8")

    return table


def add_separator(doc):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("\u2500" * 60)
    run.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
    run.font.size = Pt(8)


def add_field_value(doc, label, value, label_bold=True):
    p = doc.add_paragraph()
    run_l = p.add_run(f"{label}: ")
    run_l.bold = label_bold
    run_l.font.size = Pt(10)
    run_v = p.add_run(value)
    run_v.font.size = Pt(10)
    return p


# =====================================================================
# MAIN DOCUMENT BUILD
# =====================================================================

def build_document():
    doc = Document()

    # Page setup
    section = doc.sections[0]
    section.page_width = Cm(21)
    section.page_height = Cm(29.7)
    section.top_margin = Cm(2)
    section.bottom_margin = Cm(2)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    # Styles
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(10)
    style.font.color.rgb = DARK_TEXT

    for level in range(1, 5):
        hs = doc.styles[f'Heading {level}']
        hs.font.name = 'Calibri'
        hs.font.color.rgb = AZ_MAGENTA

    # =================================================================
    # COVER PAGE
    # =================================================================
    for _ in range(6):
        doc.add_paragraph()

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("VELOX\u00ae")
    run.font.size = Pt(36)
    run.font.color.rgb = AZ_MAGENTA
    run.bold = True

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub.add_run("(veloxaban)")
    run.font.size = Pt(18)
    run.font.color.rgb = DARK_TEXT

    doc.add_paragraph()

    desc = doc.add_paragraph()
    desc.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = desc.add_run("Website Briefing")
    run.font.size = Pt(24)
    run.font.color.rgb = BRAND_COLOUR
    run.bold = True

    doc.add_paragraph()

    tagline = doc.add_paragraph()
    tagline.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = tagline.add_run("Protection without compromise.")
    run.font.size = Pt(14)
    run.font.color.rgb = BRAND_COLOUR
    run.italic = True

    doc.add_paragraph()

    for line in [
        "Document type: Final approved marketing brief for HCP website build",
        "Prepared by: Marketing \u2014 UK Cardiovascular Franchise",
        "Approval status: MLR-approved copy \u2014 do not modify",
        "Date: March 2026",
        "Approval code: GB-10247 | DOP: March 2026",
    ]:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(line)
        run.font.size = Pt(10)
        run.font.color.rgb = GREY_TEXT

    doc.add_page_break()

    # =================================================================
    # TABLE OF CONTENTS
    # =================================================================
    add_heading(doc, "Contents", level=1, color=AZ_MAGENTA)
    toc_items = [
        "1. Drug Profile",
        "2. Mechanism of Action",
        "3. Clinical Programme: VELOCITY",
        "4. Safety Profile",
        "5. Prescribing Information",
        "6. Adverse Event Reporting",
        "7. References",
        "8. Site Navigation",
        "9. Page Content",
        "   Page 1: Home",
        "   Page 2: VELOCITY Data",
        "   Page 3: Safety",
        "   Page 4: Dosing & Administration",
        "   Page 5: How VELOX Works",
        "   Page 6: Resources",
        "10. Footer Content",
        "11. Image Assets",
    ]
    for item in toc_items:
        p = doc.add_paragraph()
        run = p.add_run(item)
        run.font.size = Pt(10)
        run.font.color.rgb = DARK_TEXT

    doc.add_page_break()

    # =================================================================
    # 1. DRUG PROFILE
    # =================================================================
    add_heading(doc, "1. Drug Profile", level=1, color=AZ_MAGENTA)

    profile_data = [
        ("Brand name", "VELOX\u00ae"),
        ("Generic name", "veloxaban"),
        ("Drug class", "Selective oral Factor XIa inhibitor"),
        ("Indication", "Prevention of stroke and systemic embolism in adult patients with non-valvular atrial fibrillation (NVAF) with one or more risk factors for stroke"),
        ("Formulation", "40 mg film-coated tablet"),
        ("Dosing", "One 40 mg tablet once daily, with or without food"),
        ("Approval", "MHRA \u2014 January 2026"),
        ("Brand colour", "Deep Navy #1A365D"),
        ("Accent colour", "Crimson Red #C62828"),
        ("Approval code", "GB-10247"),
    ]
    add_table(doc, ["Field", "Detail"], profile_data)

    doc.add_paragraph()

    # Brand rules
    brand_notice = doc.add_paragraph()
    run = brand_notice.add_run(
        "VELOX brand rule: VELOX always appears in capitals, with \u00ae on first mention per page. "
        "Generic name (veloxaban) appears in lowercase parentheses on first mention. "
        'The approved tagline "Protection without compromise." may only be used verbatim \u2014 no variations permitted.'
    )
    run.bold = True
    run.font.size = Pt(9)
    run.font.color.rgb = RED_NOTICE

    add_separator(doc)

    # =================================================================
    # 2. MECHANISM OF ACTION
    # =================================================================
    add_heading(doc, "2. Mechanism of Action", level=1, color=AZ_MAGENTA)

    add_body(doc, (
        "Veloxaban is a first-in-class, selective, oral small-molecule inhibitor of activated Factor XI "
        "(Factor XIa). Factor XIa plays a central role in the amplification phase of the coagulation cascade, "
        "propagating thrombin generation through the intrinsic pathway without significantly affecting the "
        "extrinsic (tissue factor) pathway responsible for normal haemostasis."
    ))
    add_body(doc, (
        "The coagulation cascade comprises two converging pathways. The extrinsic pathway, initiated by "
        "tissue factor exposure at sites of vascular injury, is essential for physiological haemostasis \u2014 the "
        "body\u2019s primary defence against bleeding. The intrinsic pathway, driven by contact activation and "
        "amplified by Factor XIa, contributes disproportionately to pathological thrombus formation (e.g. in "
        "atrial fibrillation, venous thromboembolism) while playing a lesser role in surgical or traumatic "
        "haemostasis.\u00b9 \u00b2"
    ))
    add_body(doc, (
        "By selectively inhibiting Factor XIa, veloxaban achieves potent antithrombotic efficacy through "
        "the following mechanisms:"
    ))

    mechanisms = [
        "Suppression of thrombin amplification via the intrinsic (contact) pathway",
        "Reduction of fibrin-rich thrombus propagation in low-shear environments (e.g. left atrial appendage in AF)",
        "Attenuation of Factor XIa-driven platelet activation, reducing platelet-dependent thrombin generation",
        "Preservation of the extrinsic (tissue factor) pathway, maintaining physiological haemostasis at sites of vascular injury",
    ]
    for m in mechanisms:
        p = doc.add_paragraph(style='List Bullet')
        run = p.add_run(m)
        run.font.size = Pt(10)

    add_body(doc, (
        "This selective mechanism separates antithrombotic efficacy from bleeding risk \u2014 a limitation of "
        "current Factor Xa and direct thrombin inhibitors, which inhibit components common to both pathological "
        "and physiological coagulation. Clinical genetic evidence supports this approach: individuals with "
        "inherited Factor XI deficiency demonstrate protection from thrombotic events with only mild bleeding "
        "tendency, unlike deficiencies in Factor X or prothrombin.\u00b9 \u00b2 \u2075"
    ))

    add_separator(doc)

    # =================================================================
    # 3. CLINICAL PROGRAMME: VELOCITY
    # =================================================================
    add_heading(doc, "3. Clinical Programme: VELOCITY", level=1, color=AZ_MAGENTA)

    # VELOCITY-AF
    add_heading(doc, "VELOCITY-AF (Phase III, pivotal \u2014 Stroke prevention in atrial fibrillation)", level=2, color=AZ_MAGENTA)
    for label, val in [
        ("Design", "Randomised, double-blind, double-dummy, active-controlled, non-inferiority Phase III trial with pre-specified superiority testing for major bleeding"),
        ("Population", "14,228 adults with non-valvular atrial fibrillation and CHA\u2082DS\u2082-VASc score \u22652 (men) or \u22653 (women)"),
        ("Duration", "Median 24 months on treatment (event-driven; minimum 12 months per patient)"),
        ("Comparator", "Rivaroxaban 20 mg once daily (15 mg once daily for CrCl 30\u201349 mL/min)"),
        ("Primary efficacy endpoint", "Time to first stroke (ischaemic or haemorrhagic) or systemic embolism"),
        ("Primary safety endpoint", "Time to first ISTH major bleeding event"),
        ("Key secondary endpoints", "All-cause mortality; composite of stroke, systemic embolism, MI, or cardiovascular death; net clinical benefit (composite of stroke/SE/major bleeding/all-cause death); intracranial haemorrhage"),
        ("Publication", "Whitfield et al. N Engl J Med 2025; 393(8): 702\u2013715"),
    ]:
        add_field_value(doc, label, val)

    doc.add_paragraph()
    add_body(doc, "Key results:", bold=True)
    add_table(doc,
        ["Endpoint", "VELOX 40 mg (n=7,114)", "Rivaroxaban (n=7,114)", "Treatment effect"],
        [
            ("Stroke or SE (primary efficacy)",
             "1.68%/year", "1.72%/year",
             "HR 0.97 (0.83\u20131.14); P<0.001 for non-inferiority"),
            ("Ischaemic stroke",
             "1.32%/year", "1.38%/year",
             "HR 0.96 (0.80\u20131.15)"),
            ("Haemorrhagic stroke",
             "0.18%/year", "0.31%/year",
             "HR 0.58 (0.38\u20130.88); P=0.011"),
            ("ISTH major bleeding (primary safety)",
             "1.52%/year", "2.58%/year",
             "HR 0.59 (0.50\u20130.69); P<0.001"),
            ("Intracranial haemorrhage",
             "0.21%/year", "0.52%/year",
             "HR 0.40 (0.28\u20130.58); P<0.001"),
            ("GI major bleeding",
             "0.62%/year", "1.04%/year",
             "HR 0.60 (0.47\u20130.76); P<0.001"),
            ("All-cause mortality",
             "3.14%/year", "3.38%/year",
             "HR 0.93 (0.83\u20131.04); P=0.21"),
            ("Net clinical benefit*",
             "4.42%/year", "5.61%/year",
             "HR 0.79 (0.72\u20130.87); P<0.001"),
        ])

    p = doc.add_paragraph()
    run = p.add_run("*Net clinical benefit = composite of stroke/SE, major bleeding, and all-cause death.")
    run.font.size = Pt(8)
    run.font.italic = True
    run.font.color.rgb = GREY_TEXT

    doc.add_paragraph()

    # VELOCITY-BLEED
    add_heading(doc, "VELOCITY-BLEED (Phase III \u2014 Bleeding safety in high-risk AF patients)", level=2, color=AZ_MAGENTA)
    for label, val in [
        ("Design", "Randomised, double-blind, active-controlled Phase III trial in patients at elevated bleeding risk"),
        ("Population", "4,612 adults with NVAF and at least one additional bleeding risk factor (age \u226580; CrCl 30\u201349 mL/min; history of GI bleeding; concomitant antiplatelet therapy; HAS-BLED score \u22653)"),
        ("Duration", "52 weeks on treatment"),
        ("Comparator", "Apixaban 5 mg twice daily (2.5 mg twice daily per label)"),
        ("Primary endpoint", "ISTH major or clinically relevant non-major (CRNM) bleeding events over 52 weeks"),
        ("Key secondary endpoints", "ISTH major bleeding alone; stroke or SE; net clinical benefit; time to first CRNM bleeding"),
        ("Publication", "Nakamura et al. Lancet 2026; 407(10329): 445\u2013458"),
    ]:
        add_field_value(doc, label, val)

    doc.add_paragraph()
    add_body(doc, "Key results:", bold=True)
    add_table(doc,
        ["Endpoint", "VELOX 40 mg (n=2,306)", "Apixaban (n=2,306)", "Treatment effect"],
        [
            ("Major or CRNM bleeding (primary)",
             "4.12%", "6.97%",
             "HR 0.59 (0.49\u20130.71); P<0.001"),
            ("ISTH major bleeding",
             "1.34%", "2.28%",
             "HR 0.59 (0.42\u20130.82); P=0.002"),
            ("Stroke or SE",
             "1.82%", "1.74%",
             "HR 1.05 (0.77\u20131.42); P=0.76 (non-inferior)"),
            ("Intracranial haemorrhage",
             "0.22%", "0.48%",
             "HR 0.46 (0.23\u20130.90); P=0.024"),
            ("GI bleeding (major + CRNM)",
             "1.74%", "2.89%",
             "HR 0.60 (0.44\u20130.82); P=0.001"),
            ("Net clinical benefit",
             "6.81%", "8.92%",
             "HR 0.76 (0.66\u20130.88); P<0.001"),
        ])

    add_separator(doc)

    # =================================================================
    # 4. SAFETY PROFILE
    # =================================================================
    add_heading(doc, "4. Safety Profile (Pooled VELOCITY data, N=9,420 VELOX)", level=1, color=AZ_MAGENTA)

    add_heading(doc, "Most common adverse events (\u22652%)", level=2, color=AZ_MAGENTA)
    add_table(doc,
        ["Adverse event", "VELOX (%)", "Comparator (%)"],
        [
            ("Nasopharyngitis", "7.2", "7.0"),
            ("Epistaxis", "4.8", "5.6"),
            ("Contusion/bruising", "4.1", "5.9"),
            ("Gingival bleeding", "3.4", "4.2"),
            ("Haematuria", "2.8", "3.7"),
            ("Dizziness", "2.6", "2.4"),
            ("Dyspepsia", "2.3", "2.1"),
            ("Diarrhoea", "2.1", "1.9"),
        ])

    doc.add_paragraph()

    add_heading(doc, "Bleeding events (pooled VELOCITY-AF + VELOCITY-BLEED)", level=2, color=AZ_MAGENTA)
    add_body(doc, (
        "VELOX demonstrated a consistently lower bleeding rate across all categories compared with "
        "established Factor Xa inhibitors. ISTH major bleeding occurred in 1.52%/year (VELOCITY-AF) and "
        "1.34% (VELOCITY-BLEED) of VELOX-treated patients, representing 41% relative risk reductions "
        "versus rivaroxaban and apixaban respectively. Intracranial haemorrhage, the most feared "
        "complication of anticoagulation, was reduced by 54\u201360% with VELOX across both trials.\u00b9 \u00b2"
    ))

    doc.add_paragraph()

    add_heading(doc, "Hepatic safety", level=2, color=AZ_MAGENTA)
    add_body(doc, (
        "ALT elevations >3\u00d7 ULN occurred in 1.1% of VELOX-treated patients vs 0.9% comparator across "
        "pooled data. No cases of Hy\u2019s Law were observed. Routine hepatic monitoring is not required, but "
        "liver function should be assessed prior to initiation and if clinically indicated during treatment.\u00b3"
    ))

    doc.add_paragraph()

    add_heading(doc, "Key safety findings", level=2, color=AZ_MAGENTA)
    safety_findings = [
        ("Serious adverse events", "12.4% VELOX vs 13.8% comparator (driven by fewer bleeding-related hospitalisations)"),
        ("Treatment discontinuation due to AEs", "4.8% vs 5.4%"),
        ("All-cause mortality", "3.14%/year vs 3.38%/year in VELOCITY-AF (HR 0.93; P=0.21)"),
        ("Myocardial infarction", "0.84%/year vs 0.91%/year (no increase in coronary events)"),
        ("Drug interactions", "Strong dual CYP3A4/P-gp inhibitors (ketoconazole, ritonavir) increase veloxaban exposure ~2.1-fold; avoid concomitant use. Moderate CYP3A4 inhibitors (diltiazem, erythromycin): no dose adjustment required\u00b3"),
        ("Renal impairment", "No dose adjustment for CrCl \u226530 mL/min. Not studied in CrCl <30 mL/min or dialysis. Contraindicated in CrCl <15 mL/min\u00b3"),
    ]
    for label, val in safety_findings:
        p = doc.add_paragraph()
        run_l = p.add_run(f"{label}: ")
        run_l.bold = True
        run_l.font.size = Pt(10)
        run_v = p.add_run(val)
        run_v.font.size = Pt(10)

    doc.add_paragraph()

    add_heading(doc, "Special populations", level=2, color=AZ_MAGENTA)
    special_pops = [
        "Elderly (\u226575 years): 38% of VELOCITY-AF patients were \u226575 years. Efficacy and safety consistent with the overall population. No dose adjustment required.\u00b3",
        "Renal impairment (CrCl 30\u201349 mL/min): No dose reduction required (unlike rivaroxaban). In the renal impairment subgroup of VELOCITY-AF, major bleeding was 1.64%/year vs 3.12%/year for rivaroxaban.\u00b9 \u00b3",
        "Low body weight (<60 kg): Exposure modestly increased (1.3-fold). No dose adjustment required based on VELOCITY-AF subgroup analysis showing consistent efficacy and safety.\u00b3",
        "Hepatic impairment: Not recommended in Child-Pugh C. No dose adjustment for Child-Pugh A or B.\u00b3",
        "Concomitant antiplatelet therapy: 14% of VELOCITY-AF patients received aspirin. Bleeding increase with dual therapy was smaller with VELOX than rivaroxaban. Triple therapy (DAPT + anticoagulant) was excluded from trials.\u00b3",
    ]
    for sp in special_pops:
        p = doc.add_paragraph(style='List Bullet')
        colon_idx = sp.index(":")
        run_b = p.add_run(sp[:colon_idx + 1])
        run_b.bold = True
        run_b.font.size = Pt(10)
        run_v = p.add_run(sp[colon_idx + 1:])
        run_v.font.size = Pt(10)

    add_separator(doc)

    # =================================================================
    # 5. PRESCRIBING INFORMATION
    # =================================================================
    add_heading(doc, "5. Prescribing Information (abbreviated \u2014 for every page footer)", level=1, color=AZ_MAGENTA)

    pi_text = (
        "VELOX (veloxaban) 40 mg film-coated tablets. "
        "Please refer to the Summary of Product Characteristics (SmPC) before prescribing. "
        "Indication: Prevention of stroke and systemic embolism in adult patients with non-valvular "
        "atrial fibrillation with one or more risk factors for stroke (prior stroke/TIA/SE, age \u226575 years, "
        "hypertension, diabetes mellitus, heart failure NYHA \u2265II). "
        "Dosage and administration: 40 mg once daily, with or without food. Swallow whole; do not crush, "
        "split, or chew. No dose adjustment required for age, body weight, or renal impairment (CrCl \u226530 mL/min). "
        "Contraindicated in CrCl <15 mL/min. "
        "Contraindications: Hypersensitivity to veloxaban or excipients; active clinically significant bleeding; "
        "hepatic disease associated with coagulopathy (Child-Pugh C); concomitant treatment with strong dual "
        "CYP3A4/P-gp inhibitors; lesion or condition at significant risk of major bleeding; prosthetic heart valve "
        "requiring anticoagulant treatment. "
        "Warnings and precautions: Assess renal function before initiation and when clinically indicated during "
        "treatment. Discontinue if severe hepatic impairment develops. If switching from a vitamin K antagonist, "
        "discontinue VKA and start VELOX when INR <2.0. Reversal: No specific antidote; andexanet alfa is not "
        "expected to reverse veloxaban. Manage major bleeding with standard supportive measures and consider "
        "prothrombin complex concentrate. "
        "Interactions: Avoid strong dual CYP3A4/P-gp inhibitors (ketoconazole, itraconazole, ritonavir). "
        "Strong CYP3A4/P-gp inducers (rifampicin, carbamazepine, phenytoin) may reduce efficacy; avoid "
        "concomitant use. "
        "Side effects: Common (\u22651/100 to <1/10): epistaxis, contusion, gingival bleeding, haematuria. "
        "Uncommon (\u22651/1000 to <1/100): intracranial haemorrhage, gastrointestinal haemorrhage, ALT increase. "
        "Legal category: POM. Pack and price: 28 tablets (40 mg): \u00a358.80; 56 tablets (40 mg): \u00a3117.60. "
        "Marketing authorisation holder: AstraZeneca UK Ltd. MA number: PLGB 17901/0721. "
        "Full prescribing information available from: AstraZeneca UK Ltd, 2 Pancras Square, London N1C 4AG. "
        "GB-10247 | DOP: March 2026."
    )
    add_body(doc, pi_text, size=Pt(9))

    add_separator(doc)

    # =================================================================
    # 6. ADVERSE EVENT REPORTING
    # =================================================================
    add_heading(doc, "6. Adverse Event Reporting (for every page footer)", level=1, color=AZ_MAGENTA)
    add_body(doc, (
        "Adverse events should be reported. Reporting forms and information can be found at "
        "www.mhra.gov.uk/yellowcard or search for MHRA Yellow Card in the Google Play or Apple App Store. "
        "Adverse events should also be reported to AstraZeneca by visiting contactazmedical.astrazeneca.com "
        "or by calling 0800 783 0033."
    ))

    add_separator(doc)

    # =================================================================
    # 7. REFERENCES
    # =================================================================
    add_heading(doc, "7. References (for every page footer)", level=1, color=AZ_MAGENTA)
    refs = [
        "Whitfield et al. N Engl J Med 2025; 393(8): 702\u2013715.",
        "Nakamura et al. Lancet 2026; 407(10329): 445\u2013458.",
        "VELOX (veloxaban) Summary of Product Characteristics. AstraZeneca UK Ltd. January 2026.",
        "Weitz JI, Fredenburgh JC. J Clin Invest 2022; 132(7): e157706.",
        "Gr\u00fcnberg M, et al. Blood 2021; 137(6): 767\u2013778.",
    ]
    for i, ref in enumerate(refs, 1):
        p = doc.add_paragraph()
        run = p.add_run(f"{i}.  {ref}")
        run.font.size = Pt(10)
        run.italic = True

    add_separator(doc)

    # =================================================================
    # 8. SITE NAVIGATION
    # =================================================================
    add_heading(doc, "8. Site Navigation", level=1, color=AZ_MAGENTA)

    nav_items = [
        ("Top bar links", "Contact Us (https://www.astrazeneca.co.uk/contact-us.html) | AZ Employee Login (https://login.astrazeneca.com)"),
        ("Main navigation pages", "VELOCITY Data | Safety | Dosing & Administration | How VELOX Works | Resources"),
        ("Utility", "Search | Login"),
    ]
    for label, val in nav_items:
        add_field_value(doc, label, val)

    doc.add_page_break()

    # =================================================================
    # 9. PAGE CONTENT
    # =================================================================
    add_heading(doc, "9. Page Content", level=1, color=AZ_MAGENTA)

    notice = doc.add_paragraph()
    run = notice.add_run(
        "IMPORTANT: All copy below is final and MLR-approved. It must be used exactly as written \u2014 "
        "do not modify, rephrase, or abbreviate any text. All superscript reference numbers, statistical "
        "values, and regulatory language must be reproduced verbatim."
    )
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RED_NOTICE

    notice2 = doc.add_paragraph()
    run = notice2.add_run(
        "Each page must end with expandable sections for Prescribing Information, Adverse Event Reporting, "
        "and References (see sections 5, 6, and 7 above)."
    )
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RED_NOTICE

    notice3 = doc.add_paragraph()
    run = notice3.add_run(
        'VELOX brand rule: VELOX always appears in capitals, with \u00ae on first mention per page. '
        'Generic name (veloxaban) in lowercase parentheses on first mention. '
        'Tagline "Protection without compromise." verbatim only.'
    )
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RED_NOTICE

    add_separator(doc)

    # =====================================================================
    # PAGE 1: HOME
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 1: Home", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/velox/")
    add_separator(doc)

    # Section 1 — Hero
    add_heading(doc, "Section 1 \u2014 Hero (full-width image with text overlay)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "hero-teaser")
    doc.add_paragraph()
    add_image_with_caption(doc, "hero-home.jpeg", width=Inches(5.5))

    add_field_value(doc, "Heading", "VELOX\u00ae (veloxaban)")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "The first oral Factor XIa inhibitor for stroke prevention in atrial fibrillation. "
        "Non-inferior stroke protection with 41% fewer major bleeds versus rivaroxaban. "
        "Protection without compromise.\u00b9"
    )
    add_field_value(doc, "Call to action", "Explore the VELOCITY data \u2192 /velox/velocity-data")

    add_separator(doc)

    # Section 2 — Key benefit cards
    add_heading(doc, "Section 2 \u2014 Three key benefit cards (equal columns)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "cards-teaser")

    # Card 1 — Stroke prevention
    doc.add_paragraph()
    add_image_with_caption(doc, "card-stroke.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Non-inferior stroke prevention")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "In VELOCITY-AF, VELOX demonstrated non-inferior efficacy to rivaroxaban for the prevention of "
        "stroke and systemic embolism (HR 0.97; 95% CI: 0.83\u20131.14; P<0.001 for non-inferiority), "
        "in 14,228 patients with non-valvular atrial fibrillation over a median 24-month treatment period.\u00b9"
    )
    add_field_value(doc, "Card link", "View VELOCITY data \u2192 /velox/velocity-data")

    add_separator(doc)

    # Card 2 — Bleeding safety
    add_image_with_caption(doc, "card-bleeding.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "41% fewer major bleeding events")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "VELOX significantly reduced ISTH major bleeding by 41% versus rivaroxaban "
        "(HR 0.59; 95% CI: 0.50\u20130.69; P<0.001). Intracranial haemorrhage was reduced by 60% "
        "(HR 0.40; P<0.001) and gastrointestinal major bleeding by 40% (HR 0.60; P<0.001).\u00b9"
    )
    add_field_value(doc, "Card link", "Explore safety profile \u2192 /velox/safety")

    add_separator(doc)

    # Card 3 — Simple dosing
    add_image_with_caption(doc, "card-dosing.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Simple once-daily dosing")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "One 40 mg tablet once daily, with or without food. No dose adjustment for age, body weight, "
        "or renal impairment (CrCl \u226530 mL/min). A simplified regimen designed to support adherence "
        "and reduce prescribing complexity.\u00b3"
    )
    add_field_value(doc, "Card link", "View dosing information \u2192 /velox/dosing")

    add_separator(doc)

    # Section 3 — Disease context
    add_heading(doc, "Section 3 \u2014 Disease context (centred text) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "The bleeding dilemma in atrial fibrillation")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Atrial fibrillation affects over 1.4 million people in the UK and is a leading cause of "
        "ischaemic stroke.\u2074 While direct oral anticoagulants have transformed stroke prevention, "
        "major bleeding remains the principal safety concern and the most common reason for treatment "
        "discontinuation or dose reduction in clinical practice. Factor XIa inhibition offers a "
        "fundamentally different approach: targeting pathological thrombosis through the intrinsic "
        "coagulation pathway while preserving haemostatic capacity.\u2074 \u2075"
    )

    add_separator(doc)

    # Section 4 — Mechanism teaser
    add_heading(doc, "Section 4 \u2014 Mechanism teaser (two-column: image left, text right) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-moa-preview.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Separating thrombosis from haemostasis")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Factor XIa amplifies pathological thrombus formation through the intrinsic coagulation pathway, "
        "but plays a limited role in haemostasis at sites of vascular injury. By selectively inhibiting "
        "Factor XIa, VELOX provides potent antithrombotic protection while preserving the extrinsic "
        "pathway that maintains normal blood clotting.\u00b3 \u2075"
    )
    add_field_value(doc, "Call to action", "Explore how VELOX works \u2192 /velox/how-velox-works")

    add_separator(doc)

    # Section 5 — Accordion
    add_heading(doc, "Section 5 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "accordion")
    add_body(doc, "Expandable sections for: Prescribing Information | Adverse Event Reporting | References (Use approved text from sections 5, 6, and 7 above)", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: VELOX (veloxaban) | Stroke Prevention in AF | AstraZeneca UK")
    add_body(doc, "Description: VELOX (veloxaban) is a first-in-class oral Factor XIa inhibitor for stroke prevention in non-valvular atrial fibrillation. Explore VELOCITY clinical data, safety, and dosing for UK healthcare professionals.")

    # =====================================================================
    # PAGE 2: VELOCITY DATA
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 2: VELOCITY Data", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/velox/velocity-data")
    add_separator(doc)

    # Hero
    add_heading(doc, "Section 1 \u2014 Hero (full-width image with text overlay)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "hero-teaser")
    doc.add_paragraph()
    add_image_with_caption(doc, "hero-efficacy.jpeg", width=Inches(5.5))

    add_field_value(doc, "Heading", "The VELOCITY clinical programme")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "VELOX\u00ae (veloxaban) was evaluated in over 18,000 patients across two landmark Phase III trials, "
        "demonstrating non-inferior stroke prevention with significantly fewer bleeding events than "
        "established Factor Xa inhibitors.\u00b9 \u00b2"
    )

    add_separator(doc)

    # Programme overview
    add_heading(doc, "Section 2 \u2014 Programme overview (centred text) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "Redefining the anticoagulation risk\u2013benefit balance")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "The VELOCITY programme was designed to evaluate whether selective Factor XIa inhibition can "
        "maintain effective stroke prevention while fundamentally reducing bleeding risk. VELOCITY-AF "
        "assessed stroke prevention in 14,228 patients with NVAF against rivaroxaban. VELOCITY-BLEED "
        "assessed bleeding safety in 4,612 high-risk AF patients against apixaban \u2014 the comparator "
        "with the lowest established bleeding rate among Factor Xa inhibitors.\u00b9 \u00b2"
    )

    add_separator(doc)

    # Tabs
    add_heading(doc, "Section 3 \u2014 Clinical data (two tabs)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "tabs-large")

    # Tab 1 — VELOCITY-AF
    doc.add_paragraph()
    add_body(doc, 'Tab 1: "VELOCITY-AF: Stroke prevention"', bold=True)
    add_image_with_caption(doc, "tab-velocity-af.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "VELOCITY-AF: Non-inferior stroke prevention, 41% fewer major bleeds")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "VELOCITY-AF was a randomised, double-blind, double-dummy, active-controlled trial comparing "
        "VELOX 40 mg once daily with rivaroxaban 20 mg once daily in 14,228 adults with non-valvular "
        "atrial fibrillation and CHA\u2082DS\u2082-VASc score \u22652 (men) or \u22653 (women), treated for a "
        "median of 24 months.\u00b9"
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Body text (continued): ")
    run.bold = True
    p.add_run(
        "VELOX met its primary efficacy endpoint, demonstrating non-inferiority to rivaroxaban for "
        "the prevention of stroke and systemic embolism (1.68%/year vs 1.72%/year; HR 0.97; 95% CI: "
        "0.83\u20131.14; P<0.001 for non-inferiority). Haemorrhagic stroke was reduced by 42% (HR 0.58; "
        "P=0.011). For the primary safety endpoint, ISTH major bleeding was reduced by 41% (1.52%/year "
        "vs 2.58%/year; HR 0.59; P<0.001). Intracranial haemorrhage was reduced by 60% (HR 0.40; "
        "P<0.001) and GI major bleeding by 40% (HR 0.60; P<0.001). The net clinical benefit composite "
        "favoured VELOX (HR 0.79; P<0.001).\u00b9"
    )

    add_body(doc, "Data table:", bold=True)
    add_table(doc,
        ["Endpoint", "VELOX (n=7,114)", "Rivaroxaban (n=7,114)", "Treatment effect"],
        [
            ("Stroke or SE", "1.68%/year", "1.72%/year", "HR 0.97 (0.83\u20131.14); P\u2060NI<0.001"),
            ("ISTH major bleeding", "1.52%/year", "2.58%/year", "HR 0.59 (0.50\u20130.69); P<0.001"),
            ("Intracranial haemorrhage", "0.21%/year", "0.52%/year", "HR 0.40 (0.28\u20130.58); P<0.001"),
            ("GI major bleeding", "0.62%/year", "1.04%/year", "HR 0.60 (0.47\u20130.76); P<0.001"),
            ("Net clinical benefit", "4.42%/year", "5.61%/year", "HR 0.79 (0.72\u20130.87); P<0.001"),
        ])

    add_separator(doc)

    # Tab 2 — VELOCITY-BLEED
    add_body(doc, 'Tab 2: "VELOCITY-BLEED: Bleeding safety in high-risk patients"', bold=True)
    add_image_with_caption(doc, "tab-velocity-bleed.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "VELOCITY-BLEED: Superior bleeding safety in high-risk AF patients")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "VELOCITY-BLEED was a randomised, double-blind, active-controlled trial comparing VELOX 40 mg "
        "once daily with apixaban (5 mg or 2.5 mg twice daily per label) in 4,612 adults with NVAF and "
        "at least one additional bleeding risk factor (age \u226580; CrCl 30\u201349 mL/min; history of GI "
        "bleeding; concomitant antiplatelet; HAS-BLED \u22653) over 52 weeks.\u00b2"
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Body text (continued): ")
    run.bold = True
    p.add_run(
        "VELOX demonstrated a 41% reduction in the primary endpoint of ISTH major or clinically relevant "
        "non-major bleeding versus apixaban (4.12% vs 6.97%; HR 0.59; 95% CI: 0.49\u20130.71; P<0.001). "
        "Major bleeding alone was reduced by 41% (HR 0.59; P=0.002). Intracranial haemorrhage was reduced "
        "by 54% (HR 0.46; P=0.024). Stroke and systemic embolism rates were non-inferior to apixaban "
        "(1.82% vs 1.74%; HR 1.05; 95% CI: 0.77\u20131.42). The net clinical benefit favoured VELOX "
        "(HR 0.76; P<0.001).\u00b2"
    )

    add_body(doc, "Data table:", bold=True)
    add_table(doc,
        ["Endpoint", "VELOX (n=2,306)", "Apixaban (n=2,306)", "Treatment effect"],
        [
            ("Major or CRNM bleeding", "4.12%", "6.97%", "HR 0.59 (0.49\u20130.71); P<0.001"),
            ("ISTH major bleeding", "1.34%", "2.28%", "HR 0.59 (0.42\u20130.82); P=0.002"),
            ("Stroke or SE", "1.82%", "1.74%", "HR 1.05 (0.77\u20131.42); non-inferior"),
            ("Intracranial haemorrhage", "0.22%", "0.48%", "HR 0.46 (0.23\u20130.90); P=0.024"),
            ("Net clinical benefit", "6.81%", "8.92%", "HR 0.76 (0.66\u20130.88); P<0.001"),
        ])

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 4 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: VELOCITY Data | VELOX (veloxaban) | Stroke Prevention & Bleeding Safety | AstraZeneca UK")
    add_body(doc, "Description: Explore the VELOCITY clinical programme for VELOX (veloxaban) \u2014 Phase III stroke prevention and bleeding safety data in patients with non-valvular atrial fibrillation.")

    # =====================================================================
    # PAGE 3: SAFETY
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 3: Safety", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/velox/safety")
    add_separator(doc)

    # Title block
    add_heading(doc, "Section 1 \u2014 Page header (text only, no image)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "title")
    add_field_value(doc, "Heading", "Safety profile of VELOX")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "VELOX\u00ae (veloxaban) has been evaluated in over 9,400 patients across the VELOCITY clinical "
        "programme, with treatment durations of up to 24 months.\u00b9 \u00b2 \u00b3"
    )

    add_separator(doc)

    # Key safety message
    add_heading(doc, "Section 2 \u2014 Key safety message (centred text) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "A new safety paradigm in anticoagulation")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "By targeting Factor XIa \u2014 a key driver of pathological thrombus formation that plays a limited "
        "role in normal haemostasis \u2014 VELOX achieves a fundamentally different safety profile from "
        "established anticoagulants. In VELOCITY-AF, serious adverse events were lower with VELOX than "
        "rivaroxaban (12.4% vs 13.8%), driven primarily by fewer bleeding-related hospitalisations. "
        "Treatment discontinuation due to adverse events was low (4.8% vs 5.4%).\u00b9 \u00b2 \u00b3"
    )

    add_separator(doc)

    # Safety cards
    add_heading(doc, "Section 3 \u2014 Safety topic cards (three equal columns)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "cards-teaser")

    # Card 1 — Bleeding
    doc.add_paragraph()
    add_image_with_caption(doc, "card-bleeding-events.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Bleeding events")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "ISTH major bleeding: 1.52%/year (VELOX) vs 2.58%/year (rivaroxaban) in VELOCITY-AF "
        "(HR 0.59; P<0.001). In the high-bleeding-risk VELOCITY-BLEED population, major or CRNM "
        "bleeding was 4.12% vs 6.97% vs apixaban (HR 0.59; P<0.001). Intracranial haemorrhage was "
        "reduced by 54\u201360% across both trials.\u00b9 \u00b2"
    )

    add_separator(doc)

    # Card 2 — Hepatic
    add_image_with_caption(doc, "card-hepatic.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Hepatic safety")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "ALT elevations >3\u00d7 ULN occurred in 1.1% of VELOX-treated patients across pooled VELOCITY data, "
        "comparable to 0.9% with comparators. No cases meeting Hy\u2019s Law criteria were observed. Routine "
        "hepatic monitoring is not required; assess liver function before initiation and as clinically indicated.\u00b3"
    )

    add_separator(doc)

    # Card 3 — GI events
    add_image_with_caption(doc, "card-gi-events.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Gastrointestinal events")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Dyspepsia (2.3%) and diarrhoea (2.1%) were the most common non-bleeding GI adverse events. "
        "GI major bleeding was reduced by 40% versus rivaroxaban in VELOCITY-AF (0.62%/year vs 1.04%/year; "
        "HR 0.60; P<0.001) and by 40% versus apixaban in VELOCITY-BLEED (HR 0.60; P=0.001).\u00b9 \u00b2"
    )

    add_separator(doc)

    # Section 4 — AE table
    add_heading(doc, "Section 4 \u2014 Adverse events table | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "table-data")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "Most common adverse events (\u22652%) \u2014 pooled VELOCITY data")

    add_table(doc,
        ["Adverse event", "VELOX (%)", "Comparator (%)"],
        [
            ("Nasopharyngitis", "7.2", "7.0"),
            ("Epistaxis", "4.8", "5.6"),
            ("Contusion/bruising", "4.1", "5.9"),
            ("Gingival bleeding", "3.4", "4.2"),
            ("Haematuria", "2.8", "3.7"),
            ("Dizziness", "2.6", "2.4"),
            ("Dyspepsia", "2.3", "2.1"),
            ("Diarrhoea", "2.1", "1.9"),
        ])

    add_separator(doc)

    # Section 5 — Special populations
    add_heading(doc, "Section 5 \u2014 Special populations (two-column: image left, text right)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")

    add_field_value(doc, "Heading", "Consistent safety across key subgroups")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "In VELOCITY-AF, the bleeding benefit of VELOX over rivaroxaban was consistent across pre-specified "
        "subgroups including patients aged \u226575 years, those with moderate renal impairment "
        "(CrCl 30\u201349 mL/min), patients receiving concomitant antiplatelet therapy, and those with prior "
        "GI bleeding. In every subgroup, major bleeding rates were numerically or significantly lower with "
        "VELOX while stroke prevention efficacy was maintained.\u00b9 \u00b3"
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 6 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: Safety Profile | VELOX (veloxaban) | Bleeding & Adverse Events | AstraZeneca UK")
    add_body(doc, "Description: Review the safety profile of VELOX (veloxaban), including bleeding events, hepatic safety, and adverse event data from the VELOCITY clinical programme in over 9,400 patients with atrial fibrillation.")

    # =====================================================================
    # PAGE 4: DOSING & ADMINISTRATION
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 4: Dosing & Administration", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/velox/dosing")
    add_separator(doc)

    # Title block
    add_heading(doc, "Section 1 \u2014 Page header (text only, no image)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "title")
    add_field_value(doc, "Heading", "Dosing and administration")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "VELOX\u00ae (veloxaban) offers a simplified dosing regimen with no routine dose adjustments "
        "required for age, body weight, or renal function (CrCl \u226530 mL/min).\u00b3"
    )

    add_separator(doc)

    # Key dosing message
    add_heading(doc, "Section 2 \u2014 Key dosing message (centred text) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "One dose. Once daily. No routine adjustments.")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "VELOX 40 mg once daily \u2014 taken with or without food. Unlike current DOACs, no dose "
        "reduction is required for moderate renal impairment, advanced age, or low body weight, "
        "reducing prescribing complexity and the risk of inappropriate dose modifications.\u00b3"
    )

    add_separator(doc)

    # Dosing columns
    add_heading(doc, "Section 3 \u2014 Dosing details (two-column: image left, text right)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-dosing.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Recommended dose")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "The recommended dose of VELOX is 40 mg (one tablet) taken orally once daily, with or without food. "
        "Tablets should be swallowed whole and must not be crushed, split, or chewed. If a dose is missed, "
        "it should be taken as soon as remembered on the same day. Do not take a double dose to make up for "
        "a missed dose.\u00b3"
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Body text (continued): ")
    run.bold = True
    p.add_run(
        "No dose adjustment is required for: age (including patients \u226575 and \u226580 years); body weight "
        "(including <60 kg and >120 kg); moderate renal impairment (CrCl 30\u201349 mL/min); mild to moderate "
        "hepatic impairment (Child-Pugh A or B). VELOX is contraindicated in patients with CrCl <15 mL/min "
        "and is not recommended in CrCl 15\u201329 mL/min due to lack of clinical data.\u00b3"
    )

    add_separator(doc)

    # Monitoring columns
    add_heading(doc, "Section 4 \u2014 Monitoring (two-column: image left, text right) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-monitoring.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Monitoring and practical considerations")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Routine coagulation monitoring is not required with VELOX. Assess renal function (CrCl) before "
        "initiation and at least annually during treatment, or more frequently if clinically indicated "
        "(acute illness, dehydration, intercurrent renal disease). Assess hepatic function before initiation; "
        "routine hepatic monitoring during treatment is not required.\u00b3"
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Body text (continued): ")
    run.bold = True
    p.add_run(
        "Switching from warfarin: Discontinue warfarin and start VELOX when INR falls below 2.0. "
        "Switching from rivaroxaban, apixaban, edoxaban, or dabigatran: Start VELOX at the time of the "
        "next scheduled dose of the previous anticoagulant. "
        "Perioperative management: Discontinue VELOX at least 24 hours before elective surgery with "
        "standard bleeding risk, or 48 hours for high-bleeding-risk procedures. Resume when adequate "
        "haemostasis is established, typically within 24 hours post-procedure.\u00b3"
    )

    add_separator(doc)

    # Drug interactions
    add_heading(doc, "Section 5 \u2014 Drug interactions (centred text)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")

    add_field_value(doc, "Heading", "Key drug interactions")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Avoid concomitant use with strong dual CYP3A4/P-gp inhibitors (ketoconazole, itraconazole, "
        "ritonavir, lopinavir) \u2014 these increase veloxaban exposure approximately 2.1-fold. Avoid strong "
        "CYP3A4/P-gp inducers (rifampicin, carbamazepine, phenytoin, St John\u2019s wort) as these may reduce "
        "efficacy. No dose adjustment is required with moderate CYP3A4 inhibitors (diltiazem, verapamil, "
        "erythromycin) or with PPIs, H\u2082-receptor antagonists, or antacids.\u00b3"
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 6 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: Dosing & Administration | VELOX (veloxaban) | Once Daily, No Adjustments | AstraZeneca UK")
    add_body(doc, "Description: VELOX (veloxaban) dosing and administration guide: 40 mg once daily with no routine dose adjustments for age, weight, or renal function. Switching, monitoring, and drug interaction guidance for UK healthcare professionals.")

    # =====================================================================
    # PAGE 5: HOW VELOX WORKS
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 5: How VELOX Works", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/velox/how-velox-works")
    add_separator(doc)

    # Hero
    add_heading(doc, "Section 1 \u2014 Hero (full-width image with text overlay)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "hero-teaser")
    doc.add_paragraph()
    add_image_with_caption(doc, "hero-moa.jpeg", width=Inches(5.5))

    add_field_value(doc, "Heading", "How VELOX works")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "VELOX\u00ae (veloxaban) is a first-in-class selective oral Factor XIa inhibitor that separates "
        "antithrombotic efficacy from haemostatic impairment \u2014 a new approach to anticoagulation.\u00b3 \u2075"
    )

    add_separator(doc)

    # Coagulation context
    add_heading(doc, "Section 2 \u2014 Disease context (centred text) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "The coagulation cascade: two pathways, one clinical dilemma")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Current anticoagulants (Factor Xa and direct thrombin inhibitors) target components shared by "
        "both pathological thrombosis and physiological haemostasis, inherently coupling antithrombotic "
        "efficacy to bleeding risk. The intrinsic coagulation pathway \u2014 amplified by Factor XIa \u2014 "
        "contributes disproportionately to pathological thrombus formation (as seen in AF, VTE, and "
        "arterial thrombosis) while playing a limited role in the haemostatic response to vascular "
        "injury. Clinical genetic evidence confirms this: inherited Factor XI deficiency protects "
        "against thrombotic events with only mild bleeding tendency.\u2074 \u2075"
    )

    add_separator(doc)

    # MoA detail columns
    add_heading(doc, "Section 3 \u2014 Mechanism detail (two-column: image left, text right) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-moa-preview.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Selective Factor XIa inhibition: targeting the amplification loop")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Veloxaban binds selectively to the active site of Factor XIa with high affinity (Ki = 0.2 nM), "
        "suppressing thrombin amplification through the intrinsic pathway without affecting Factor Xa, "
        "thrombin, or other serine proteases in the coagulation cascade. This selective inhibition "
        "reduces fibrin-rich thrombus propagation in the low-shear environment of the left atrial "
        "appendage \u2014 the primary site of thrombus formation in AF \u2014 and attenuates Factor XIa-driven "
        "platelet activation.\u00b3 \u2075"
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Body text (continued): ")
    run.bold = True
    p.add_run(
        "Critically, veloxaban preserves the extrinsic (tissue factor) pathway, which is responsible for "
        "initiating haemostasis at sites of vascular injury. This mechanistic separation is the "
        "pharmacological basis for the reduced bleeding observed across the VELOCITY programme, including "
        "the clinically important categories of intracranial haemorrhage and gastrointestinal bleeding.\u00b3 \u2075"
    )
    add_field_value(doc, "Call to action", "View the VELOCITY bleeding data \u2192 /velox/safety")

    add_separator(doc)

    # Pharmacology
    add_heading(doc, "Section 4 \u2014 Key pharmacological properties (centred text)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")

    add_field_value(doc, "Heading", "Pharmacological profile")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Oral bioavailability: ~72%, not significantly affected by food. Time to peak plasma "
        "concentration (Tmax): 2\u20133 hours. Elimination half-life: 10\u201314 hours, supporting once-daily "
        "dosing. Metabolism: Primarily hepatic via CYP3A4, with minor renal excretion (~25% of "
        "administered dose). Protein binding: 92%. No clinically significant effect on PT, aPTT, or "
        "anti-Factor Xa assays at therapeutic concentrations, minimising interference with routine "
        "coagulation monitoring.\u00b3"
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 5 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: How VELOX Works | Factor XIa Inhibition | Mechanism of Action | AstraZeneca UK")
    add_body(doc, "Description: Understand how VELOX (veloxaban) selectively inhibits Factor XIa to separate antithrombotic efficacy from bleeding risk \u2014 a new mechanism of action in anticoagulation for atrial fibrillation.")

    # =====================================================================
    # PAGE 6: RESOURCES
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 6: Resources", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/velox/resources")
    add_separator(doc)

    # Title block
    add_heading(doc, "Section 1 \u2014 Page header (text only, no image)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "title")
    add_field_value(doc, "Heading", "Resources for healthcare professionals")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Access prescribing guides, clinical data summaries, and patient support materials for "
        "VELOX\u00ae (veloxaban). All materials are provided for UK healthcare professionals only.\u00b3"
    )

    add_separator(doc)

    # Resource cards
    add_heading(doc, "Section 2 \u2014 Resource cards (three equal columns)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "cards-teaser")

    # Card 1 — Prescribing guide
    doc.add_paragraph()
    add_image_with_caption(doc, "card-prescribing.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Prescribing guide")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "A concise clinical guide covering indication, dosing, switching, monitoring, drug interactions, "
        "special populations, and perioperative management. Designed for quick reference in clinical "
        "practice.\u00b3"
    )
    add_field_value(doc, "Card link", "Download prescribing guide \u2192 [PDF link]")

    add_separator(doc)

    # Card 2 — Clinical data summary
    add_field_value(doc, "Card heading", "VELOCITY clinical data summary")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Summary of key efficacy and safety results from VELOCITY-AF and VELOCITY-BLEED, including "
        "headline statistics, data tables, and subgroup analyses. A comprehensive overview of the "
        "clinical evidence supporting VELOX.\u00b9 \u00b2"
    )
    add_field_value(doc, "Card link", "Download data summary \u2192 [PDF link]")

    add_separator(doc)

    # Card 3 — Patient support
    add_field_value(doc, "Card heading", "Patient support materials")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Patient-facing materials to support treatment initiation conversations, including a VELOX patient "
        "information leaflet, dosing reminder card, and switching guidance card for patients transitioning "
        "from other anticoagulants."
    )
    add_field_value(doc, "Card link", "Download patient materials \u2192 [PDF link]")

    add_separator(doc)

    # Contact section
    add_heading(doc, "Section 3 \u2014 Contact (centred text) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "Medical information and support")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "For medical information enquiries about VELOX, please contact AstraZeneca Medical Information: "
        "Telephone: 0800 783 0033 | Email: medicalinformationuk@astrazeneca.com | "
        "Online: contactazmedical.astrazeneca.com"
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 4 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: Resources | VELOX (veloxaban) | Prescribing Guides & Patient Materials | AstraZeneca UK")
    add_body(doc, "Description: Access prescribing guides, VELOCITY clinical data summaries, and patient support materials for VELOX (veloxaban). For UK healthcare professionals only.")

    # =====================================================================
    # 10. FOOTER CONTENT
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "10. Footer Content", level=1, color=AZ_MAGENTA)

    add_body(doc, "The footer must appear on every page and contain the following elements:", bold=True)

    footer_items = [
        ("Logo", "AstraZeneca logo (linked to /velox/)"),
        ("Approval code", "GB-10247 | DOP: March 2026"),
        ("Copyright", "\u00a9 2026 AstraZeneca. All rights reserved. VELOX is a registered trademark of the AstraZeneca group of companies."),
        ("Page links", "VELOCITY Data | Safety | Dosing & Administration | How VELOX Works | Resources"),
        ("Regulatory links", "Report Adverse Event (https://yellowcard.mhra.gov.uk/) | Medical Information (https://contactazmedical.astrazeneca.com/) | Privacy Policy (https://www.astrazeneca.co.uk/our-company/privacy-notice.html) | Terms of Use (https://www.astrazeneca.co.uk/our-company/terms-of-use.html) | Accessibility (https://www.astrazeneca.co.uk/accessibility.html)"),
        ("Date of preparation", "Date of Preparation: March 2026"),
    ]
    for label, val in footer_items:
        add_field_value(doc, label, val)

    add_separator(doc)

    # =====================================================================
    # 11. IMAGE ASSETS
    # =====================================================================
    add_heading(doc, "11. Image Assets", level=1, color=AZ_MAGENTA)

    add_body(doc, (
        f"All images are hosted on the VELOX CDN: {CDN_BASE}/"
    ))

    doc.add_paragraph()
    add_body(doc, "Complete image manifest:", bold=True)
    doc.add_paragraph()

    img_table_rows = []
    for filename, usage in IMAGE_MANIFEST.items():
        cdn_url = f"{CDN_BASE}/{filename}"
        img_table_rows.append((filename, usage, cdn_url))

    add_table(doc,
        ["Filename", "Usage", "CDN URL"],
        img_table_rows)

    doc.add_paragraph()

    # Embed all images with previews
    add_heading(doc, "Image previews", level=2, color=AZ_MAGENTA)
    add_body(doc, "Visual previews of all 15 generated images:", italic=True)

    for filename in IMAGE_MANIFEST:
        doc.add_paragraph()
        add_body(doc, f"{filename} \u2014 {IMAGE_MANIFEST[filename]}", bold=True, size=Pt(9))
        add_image_with_caption(doc, filename, width=Inches(4))

    # --- Save ---
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    doc.save(OUTPUT_PATH)
    print(f"\n\u2705 Briefing saved to: {OUTPUT_PATH}")
    return OUTPUT_PATH


if __name__ == "__main__":
    build_document()
