#!/usr/bin/env python3
"""Generate DOCX briefing for Treluxia (trelimovab) — Anti-TSLP monoclonal antibody for Severe Asthma.

Loads images from local images/treluxia/ directory (generated by generate-images.sh).
Includes CDN URLs as captions for each image.
"""

import os
import sys
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml

# --- Configuration ---
SITE_NAME = "treluxia"
BRAND_COLOUR = RGBColor(0x00, 0x6B, 0x77)   # Deep Teal
ACCENT_COLOUR = RGBColor(0x4D, 0xAD, 0xD9)  # Sky Blue
AZ_MAGENTA = RGBColor(0x83, 0x00, 0x51)
DARK_TEXT = RGBColor(0x36, 0x3B, 0x3B)
GREY_TEXT = RGBColor(0x66, 0x66, 0x66)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
RED_NOTICE = RGBColor(0xCC, 0x00, 0x00)

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG_DIR = os.path.join(PROJECT_DIR, "images", SITE_NAME)
CDN_BASE = f"https://{SITE_NAME}-images.pages.dev"
OUTPUT_PATH = os.path.join(PROJECT_DIR, "sites", SITE_NAME, "Treluxia-Website-Briefing.docx")

# --- Image manifest (filename → usage context) ---
IMAGE_MANIFEST = {
    "hero-home.jpeg": "Home — hero",
    "hero-efficacy.jpeg": "LUMINOS Data — hero",
    "hero-dosing.jpeg": "Dosing — hero",
    "hero-moa.jpeg": "How TRELUXIA Works — hero",
    "card-exacerbations.jpeg": "Home — exacerbation reduction card",
    "card-lung-function.jpeg": "Home — lung function card",
    "card-ocs.jpeg": "Home — OCS sparing card",
    "card-isr.jpeg": "Safety — injection site reactions card",
    "card-anaphylaxis.jpeg": "Safety — anaphylaxis card",
    "card-infections.jpeg": "Safety — infections card",
    "card-prescribing-guide.jpeg": "Resources — prescribing guide card",
    "card-patient-materials.jpeg": "Resources — patient materials card",
    "card-clinical-data.jpeg": "Resources — clinical data card",
    "columns-moa-preview.jpeg": "Home — MoA teaser",
    "columns-dosing.jpeg": "Dosing — regimen",
    "columns-admin.jpeg": "Dosing — administration",
    "columns-ocs-management.jpeg": "Dosing — OCS management",
    "columns-tslp-pathway.jpeg": "MoA — TSLP pathway",
    "columns-mechanism.jpeg": "MoA — TRELUXIA mechanism",
    "columns-positioning.jpeg": "MoA — treatment positioning",
    "columns-special-pops.jpeg": "Safety — special populations",
    "columns-contact.jpeg": "Resources — contact",
    "tab-luminos1.jpeg": "LUMINOS Data — exacerbation tab",
    "tab-luminos-ocs.jpeg": "LUMINOS Data — OCS sparing tab",
}


# --- Document helpers ---

def set_cell_shading(cell, color_hex):
    shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>')
    cell._tc.get_or_add_tcPr().append(shading)


def add_heading(doc, text, level=1, color=None):
    h = doc.add_heading(text, level=level)
    if color:
        for run in h.runs:
            run.font.color.rgb = color
    return h


def add_body(doc, text, bold=False, italic=False, size=Pt(10)):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = size
    run.font.color.rgb = DARK_TEXT
    run.bold = bold
    run.italic = italic
    return p


def add_image_with_caption(doc, filename, width=Inches(4.5)):
    """Add image from local file with CDN URL caption."""
    local_path = os.path.join(IMG_DIR, filename)
    cdn_url = f"{CDN_BASE}/{filename}"
    usage = IMAGE_MANIFEST.get(filename, "")

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    if os.path.isfile(local_path) and os.path.getsize(local_path) > 1000:
        run = p.add_run()
        try:
            run.add_picture(local_path, width=width)
            print(f"  [OK] {filename}")
        except Exception as e:
            run = p.add_run(f"[Image: {filename} — file exists but embed failed: {e}]")
            run.font.color.rgb = GREY_TEXT
            run.font.size = Pt(9)
            run.italic = True
    else:
        run = p.add_run(f"[Image: {filename} — not yet generated]")
        run.font.color.rgb = GREY_TEXT
        run.font.size = Pt(9)
        run.italic = True
        print(f"  [SKIP] {filename} — not found at {local_path}")

    # CDN URL caption
    cap = doc.add_paragraph()
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = cap.add_run(cdn_url)
    r.font.size = Pt(8)
    r.font.color.rgb = RGBColor(0x00, 0x55, 0x99)
    r.underline = True

    # Usage context
    if usage:
        usage_p = doc.add_paragraph()
        usage_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r2 = usage_p.add_run(f"Usage: {usage}")
        r2.font.size = Pt(8)
        r2.font.color.rgb = GREY_TEXT
        r2.italic = True

    return p


def add_table(doc, headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = 'Table Grid'

    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = ""
        p = cell.paragraphs[0]
        run = p.add_run(h)
        run.bold = True
        run.font.size = Pt(9)
        run.font.color.rgb = WHITE
        set_cell_shading(cell, "830051")

    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = ""
            p = cell.paragraphs[0]
            run = p.add_run(str(val))
            run.font.size = Pt(9)
            run.font.color.rgb = DARK_TEXT
            if r_idx % 2 == 1:
                set_cell_shading(cell, "F8F8F8")

    return table


def add_separator(doc):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("\u2500" * 60)
    run.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
    run.font.size = Pt(8)


def add_field_value(doc, label, value, label_bold=True):
    p = doc.add_paragraph()
    run_l = p.add_run(f"{label}: ")
    run_l.bold = label_bold
    run_l.font.size = Pt(10)
    run_v = p.add_run(value)
    run_v.font.size = Pt(10)
    return p


# =====================================================================
# MAIN DOCUMENT BUILD
# =====================================================================

def build_document():
    doc = Document()

    # Page setup
    section = doc.sections[0]
    section.page_width = Cm(21)
    section.page_height = Cm(29.7)
    section.top_margin = Cm(2)
    section.bottom_margin = Cm(2)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    # Styles
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(10)
    style.font.color.rgb = DARK_TEXT

    for level in range(1, 5):
        hs = doc.styles[f'Heading {level}']
        hs.font.name = 'Calibri'
        hs.font.color.rgb = AZ_MAGENTA

    # =================================================================
    # COVER PAGE
    # =================================================================
    for _ in range(6):
        doc.add_paragraph()

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("TRELUXIA\u2122")
    run.font.size = Pt(36)
    run.font.color.rgb = AZ_MAGENTA
    run.bold = True

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub.add_run("(trelimovab)")
    run.font.size = Pt(18)
    run.font.color.rgb = DARK_TEXT

    doc.add_paragraph()

    desc = doc.add_paragraph()
    desc.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = desc.add_run("Website Briefing")
    run.font.size = Pt(24)
    run.font.color.rgb = BRAND_COLOUR
    run.bold = True

    doc.add_paragraph()

    tagline = doc.add_paragraph()
    tagline.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = tagline.add_run("Breathe beyond limits.")
    run.font.size = Pt(14)
    run.font.color.rgb = BRAND_COLOUR
    run.italic = True

    doc.add_paragraph()

    for line in [
        "Document type: Final approved marketing brief for HCP website build",
        "Prepared by: Marketing \u2014 UK Respiratory Franchise",
        "Approval status: MLR-approved copy \u2014 do not modify",
        "Date: March 2026",
        "Approval code: GB-98204 | DOP: March 2026",
    ]:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(line)
        run.font.size = Pt(10)
        run.font.color.rgb = GREY_TEXT

    doc.add_page_break()

    # =================================================================
    # TABLE OF CONTENTS
    # =================================================================
    add_heading(doc, "Contents", level=1, color=AZ_MAGENTA)
    toc_items = [
        "1. Drug Profile",
        "2. Mechanism of Action",
        "3. Clinical Programme: LUMINOS",
        "4. Safety Profile",
        "5. Prescribing Information",
        "6. Adverse Event Reporting",
        "7. References",
        "8. Site Navigation",
        "9. Page Content",
        "   Page 1: Home",
        "   Page 2: LUMINOS Data",
        "   Page 3: Safety",
        "   Page 4: Dosing & Administration",
        "   Page 5: How TRELUXIA Works",
        "   Page 6: Resources",
        "10. Footer Content",
        "11. Image Assets",
    ]
    for item in toc_items:
        p = doc.add_paragraph()
        run = p.add_run(item)
        run.font.size = Pt(10)
        run.font.color.rgb = DARK_TEXT

    doc.add_page_break()

    # =================================================================
    # 1. DRUG PROFILE
    # =================================================================
    add_heading(doc, "1. Drug Profile", level=1, color=AZ_MAGENTA)

    profile_data = [
        ("Brand name", "TRELUXIA"),
        ("Generic name", "trelimovab"),
        ("Drug class", "Human monoclonal antibody targeting thymic stromal lymphopoietin (TSLP)"),
        ("Indication", "Add-on maintenance treatment for adults and adolescents aged \u226512 years with severe asthma that is inadequately controlled despite high-dose inhaled corticosteroids plus at least one additional controller, irrespective of inflammatory phenotype"),
        ("Formulation", "210 mg/1.91 mL solution for injection in pre-filled syringe and pre-filled pen (autoinjector)"),
        ("Dosing", "210 mg subcutaneous injection once every 4 weeks"),
        ("Approval", "MHRA \u2014 January 2026"),
        ("Brand colour", "Deep Teal #006B77"),
        ("Accent colour", "Sky Blue #4DADD9"),
        ("Approval code", "GB-98204"),
    ]
    add_table(doc, ["Field", "Detail"], profile_data)

    doc.add_paragraph()

    # Brand rules
    brand_notice = doc.add_paragraph()
    run = brand_notice.add_run(
        "TRELUXIA brand rule: TRELUXIA always appears in capitals, with \u2122 on first mention per page. "
        "Generic name (trelimovab) appears in lowercase parentheses on first mention. "
        'The approved tagline "Breathe beyond limits." may only be used verbatim \u2014 no variations permitted.'
    )
    run.bold = True
    run.font.size = Pt(9)
    run.font.color.rgb = RED_NOTICE

    add_separator(doc)

    # =================================================================
    # 2. MECHANISM OF ACTION
    # =================================================================
    add_heading(doc, "2. Mechanism of Action", level=1, color=AZ_MAGENTA)

    add_body(doc, (
        "Trelimovab is a human immunoglobulin G2\u03bb monoclonal antibody that specifically binds to thymic "
        "stromal lymphopoietin (TSLP), an epithelial cytokine released at the top of the inflammatory cascade "
        "in response to airway insults including allergens, viruses, pollutants, and other triggers."
    ))
    add_body(doc, (
        "TSLP is a key upstream initiator of airway inflammation in asthma. By binding directly to TSLP and "
        "preventing its interaction with the TSLP receptor complex (TSLPR/IL-7R\u03b1), trelimovab inhibits "
        "multiple downstream inflammatory pathways:"
    ))

    tslp_effects = [
        "Eosinophilic inflammation via suppression of IL-5, IL-13, and eosinophil recruitment",
        "Type 2 (Th2) immune responses including IgE production and mast cell activation",
        "Non-type 2 inflammation including neutrophilic airway inflammation, mast cell cytokine release, and structural cell activation",
        "Airway remodelling through reduced subepithelial fibrosis and smooth muscle hypertrophy",
    ]
    for effect in tslp_effects:
        p = doc.add_paragraph(style='List Bullet')
        run = p.add_run(effect)
        run.font.size = Pt(10)

    add_body(doc, (
        "Because TSLP acts upstream of multiple inflammatory pathways, trelimovab provides broad "
        "anti-inflammatory activity across the full spectrum of severe asthma phenotypes \u2014 including "
        "patients with low eosinophil counts and those without a clearly defined type 2 inflammatory "
        "biomarker signature."
    ))

    add_separator(doc)

    # =================================================================
    # 3. CLINICAL PROGRAMME
    # =================================================================
    add_heading(doc, "3. Clinical Programme: LUMINOS", level=1, color=AZ_MAGENTA)

    # LUMINOS-1
    add_heading(doc, "LUMINOS-1 (Phase III, pivotal \u2014 Exacerbation reduction in severe asthma)", level=2, color=AZ_MAGENTA)
    for label, val in [
        ("Design", "Randomised, double-blind, placebo-controlled, parallel-group Phase III trial"),
        ("Population", "1,061 adults and adolescents aged \u226512 years with severe asthma inadequately controlled "
         "despite medium- or high-dose ICS plus at least one additional controller (LABA, LTRA, LAMA, or theophylline), "
         "with a history of \u22652 exacerbations in the prior 12 months"),
        ("Duration", "52 weeks on treatment + 12-week follow-up"),
        ("Primary endpoint", "Annualised asthma exacerbation rate (AAER) over 52 weeks"),
        ("Key secondary endpoints", "Change from baseline in pre-bronchodilator FEV\u2081 at Week 52; "
         "Asthma Control Questionnaire-6 (ACQ-6) score change at Week 52; time to first exacerbation; "
         "AAER in subgroups by baseline eosinophil count"),
        ("Publication", "Harrison et al. N Engl J Med 2025; 392(14): 1318\u20131330"),
    ]:
        add_field_value(doc, label, val)

    doc.add_paragraph()
    add_body(doc, "Key results:", bold=True)
    add_table(doc,
        ["Endpoint", "TRELUXIA (n=529)", "Placebo (n=532)", "Treatment effect"],
        [
            ("AAER (overall population)",
             "0.93", "2.10",
             "RR 0.44 (0.37\u20130.53); P<0.001"),
            ("AAER (eos \u2265300 cells/\u03bcL)",
             "0.85", "2.26",
             "RR 0.38 (0.29\u20130.49); P<0.001"),
            ("AAER (eos <300 cells/\u03bcL)",
             "1.14", "1.92",
             "RR 0.59 (0.45\u20130.78); P<0.001"),
            ("Pre-BD FEV\u2081 change at Week 52",
             "+0.29 L", "+0.04 L",
             "+0.25 L (0.18\u20130.32); P<0.001"),
            ("ACQ-6 change at Week 52",
             "\u22121.55", "\u22121.07",
             "\u22120.48 (\u22120.62 to \u22120.34); P<0.001"),
            ("Time to first exacerbation",
             "Median not reached", "36 weeks",
             "HR 0.52 (0.43\u20130.63); P<0.001"),
            ("Exacerbations requiring hospitalisation/ER",
             "0.18", "0.79",
             "RR 0.23 (0.15\u20130.35); P<0.001"),
        ])

    doc.add_paragraph()

    # LUMINOS-OCS
    add_heading(doc, "LUMINOS-OCS (Phase III \u2014 Oral corticosteroid sparing in severe asthma)", level=2, color=AZ_MAGENTA)
    for label, val in [
        ("Design", "Randomised, double-blind, placebo-controlled Phase III trial"),
        ("Population", "407 adults with severe asthma dependent on maintenance oral corticosteroids "
         "(\u22655 mg prednisolone equivalent daily), receiving high-dose ICS plus additional controllers"),
        ("Duration", "48 weeks (12-week OCS optimisation + 36-week OCS reduction phase)"),
        ("Primary endpoint", "Percentage reduction in OCS dose at Week 48 from the optimised baseline while maintaining asthma control"),
        ("Key secondary endpoints", "Proportion achieving \u226550% OCS reduction; proportion achieving complete OCS elimination; "
         "AAER during OCS reduction phase; ACQ-6 change at Week 48"),
        ("Publication", "Ventura et al. Lancet Respir Med 2026; 14(2): 112\u2013125"),
    ]:
        add_field_value(doc, label, val)

    doc.add_paragraph()
    add_body(doc, "Key results:", bold=True)
    add_table(doc,
        ["Endpoint", "TRELUXIA (n=203)", "Placebo (n=204)", "Treatment effect"],
        [
            ("Median OCS dose reduction at Week 48",
             "\u221275%", "\u221225%",
             "OR 2.58 (1.79\u20133.72); P<0.001"),
            ("\u226550% OCS reduction",
             "71.4%", "41.7%",
             "OR 3.49 (2.31\u20135.27); P<0.001"),
            ("Complete OCS elimination",
             "37.9%", "10.8%",
             "OR 5.07 (3.03\u20138.49); P<0.001"),
            ("AAER during OCS reduction phase",
             "0.76", "1.97",
             "RR 0.39 (0.28\u20130.53); P<0.001"),
            ("ACQ-6 change at Week 48",
             "\u22121.41", "\u22120.68",
             "\u22120.73 (\u22120.97 to \u22120.49); P<0.001"),
        ])

    add_separator(doc)

    # =================================================================
    # 4. SAFETY PROFILE
    # =================================================================
    add_heading(doc, "4. Safety Profile (Pooled LUMINOS data, N=732 TRELUXIA)", level=1, color=AZ_MAGENTA)

    add_heading(doc, "Most common adverse events (\u22652%)", level=2, color=AZ_MAGENTA)
    add_table(doc,
        ["Adverse event", "TRELUXIA (%)", "Placebo (%)"],
        [
            ("Nasopharyngitis", "10.4", "9.8"),
            ("Upper respiratory tract infection", "8.1", "7.4"),
            ("Headache", "6.7", "5.2"),
            ("Injection site reactions", "4.6", "2.8"),
            ("Arthralgia", "3.8", "3.1"),
            ("Back pain", "3.2", "2.6"),
            ("Pharyngitis", "2.9", "2.5"),
            ("Fatigue", "2.4", "1.9"),
        ])

    doc.add_paragraph()

    add_heading(doc, "Injection site reactions", level=2, color=AZ_MAGENTA)
    add_body(doc, (
        "Injection site reactions (ISRs) occurred in 4.6% of TRELUXIA-treated patients vs 2.8% with "
        "placebo. The most common ISRs were erythema, pain, and swelling at the injection site. All ISRs "
        "were mild to moderate in severity. No ISR led to treatment discontinuation.\u00b3"
    ))

    doc.add_paragraph()

    add_heading(doc, "Key safety findings", level=2, color=AZ_MAGENTA)
    safety_findings = [
        ("Serious adverse events", "8.4% TRELUXIA vs 11.2% placebo (driven by fewer asthma-related hospitalisations)"),
        ("Treatment discontinuation due to AEs", "2.4% vs 3.1%"),
        ("All-cause mortality", "0.1% vs 0.2% (no drug-related deaths)"),
        ("Anaphylaxis", "3 events (0.4%) in TRELUXIA vs 0 in placebo. All occurred within 24 hours; resolved with standard treatment\u00b3"),
        ("Malignancy", "0.3% vs 0.4% (no imbalance; no signal for increased risk)"),
        ("Helminth infections", "0.4% vs 0.1%. Treat pre-existing infections before initiating TRELUXIA\u00b3"),
        ("Immunogenicity", "ADAs detected in 5.1%; neutralising antibodies in 1.2%. No impact on PK, efficacy, or safety\u00b3"),
    ]
    for label, val in safety_findings:
        p = doc.add_paragraph()
        run_l = p.add_run(f"{label}: ")
        run_l.bold = True
        run_l.font.size = Pt(10)
        run_v = p.add_run(val)
        run_v.font.size = Pt(10)

    doc.add_paragraph()

    add_heading(doc, "Special populations", level=2, color=AZ_MAGENTA)
    special_pops = [
        "Adolescents (12\u201317 years): Same dose as adults (210 mg Q4W). In LUMINOS-1, 63 adolescents received TRELUXIA; efficacy and safety were consistent with the overall adult population.\u00b3",
        "Elderly (\u226565 years): No dose adjustment required. Limited data in patients \u226575 years. 11% of LUMINOS-1 patients were \u226565 years.\u00b3",
        "Renal and hepatic impairment: No dose adjustment for mild to moderate impairment. Not studied in severe renal impairment (eGFR <30 mL/min/1.73m\u00b2) or severe hepatic impairment.\u00b3",
        "Pregnancy and lactation: No adequate data in pregnant women. Human IgG crosses the placental barrier. Use only if potential benefit justifies potential risk. Unknown if excreted in human milk.\u00b3",
    ]
    for sp in special_pops:
        p = doc.add_paragraph(style='List Bullet')
        colon_idx = sp.index(":")
        run_b = p.add_run(sp[:colon_idx + 1])
        run_b.bold = True
        run_b.font.size = Pt(10)
        run_v = p.add_run(sp[colon_idx + 1:])
        run_v.font.size = Pt(10)

    add_separator(doc)

    # =================================================================
    # 5. PRESCRIBING INFORMATION
    # =================================================================
    add_heading(doc, "5. Prescribing Information (abbreviated \u2014 for every page footer)", level=1, color=AZ_MAGENTA)

    pi_text = (
        "TRELUXIA (trelimovab) 210 mg/1.91 mL solution for injection in pre-filled syringe and pre-filled pen. "
        "Please refer to the Summary of Product Characteristics (SmPC) before prescribing. Indication: Add-on "
        "maintenance treatment for adults and adolescents aged \u226512 years with severe asthma that is inadequately "
        "controlled despite high-dose inhaled corticosteroids plus at least one additional controller, irrespective "
        "of inflammatory phenotype. Dosage and administration: 210 mg administered by subcutaneous injection once "
        "every 4 weeks. Administer into the thigh, abdomen (excluding 5 cm around the navel), or upper arm (if "
        "administered by a caregiver). Rotate injection sites. The first 3 doses should be administered under the "
        "supervision of a healthcare professional. Contraindications: Hypersensitivity to trelimovab or any "
        "excipient. Warnings and precautions: Do not use to treat acute asthma symptoms or acute exacerbations. "
        "Do not abruptly discontinue systemic or inhaled corticosteroids upon initiation. Hypersensitivity reactions "
        "including anaphylaxis have been reported. Treat pre-existing helminth infections before initiating. "
        "Interactions: No formal drug interaction studies conducted. No clinically significant interactions identified. "
        "Side effects: Very common (\u22651/10): nasopharyngitis. Common (\u22651/100 to <1/10): upper respiratory tract "
        "infection, headache, injection site reactions, arthralgia. Uncommon (\u22651/1000 to <1/100): anaphylaxis, "
        "pharyngitis. Legal category: POM. Pack and price: 1 pre-filled syringe (210 mg): \u00a31,267.00; 1 pre-filled "
        "pen (210 mg): \u00a31,267.00. Marketing authorisation holder: AstraZeneca UK Ltd. MA number: PLGB 17901/0643. "
        "Full prescribing information available from: AstraZeneca UK Ltd, 2 Pancras Square, London N1C 4AG. "
        "GB-98204 | DOP: March 2026."
    )
    add_body(doc, pi_text, size=Pt(9))

    add_separator(doc)

    # =================================================================
    # 6. ADVERSE EVENT REPORTING
    # =================================================================
    add_heading(doc, "6. Adverse Event Reporting (for every page footer)", level=1, color=AZ_MAGENTA)
    add_body(doc, (
        "Adverse events should be reported. Reporting forms and information can be found at "
        "www.mhra.gov.uk/yellowcard or search for MHRA Yellow Card in the Google Play or Apple App Store. "
        "Adverse events should also be reported to AstraZeneca by visiting contactazmedical.astrazeneca.com "
        "or by calling 0800 783 0033."
    ))

    add_separator(doc)

    # =================================================================
    # 7. REFERENCES
    # =================================================================
    add_heading(doc, "7. References (for every page footer)", level=1, color=AZ_MAGENTA)
    refs = [
        "Harrison et al. N Engl J Med 2025; 392(14): 1318\u20131330.",
        "Ventura et al. Lancet Respir Med 2026; 14(2): 112\u2013125.",
        "TRELUXIA (trelimovab) Summary of Product Characteristics. AstraZeneca UK Ltd. January 2026.",
        "Global Initiative for Asthma (GINA). Global Strategy for Asthma Management and Prevention, 2025 Update.",
        "Gauvreau GM, et al. N Engl J Med 2024; 370(22): 2102\u20132110.",
    ]
    for i, ref in enumerate(refs, 1):
        p = doc.add_paragraph()
        run = p.add_run(f"{i}.  {ref}")
        run.font.size = Pt(10)
        run.italic = True

    add_separator(doc)

    # =================================================================
    # 8. SITE NAVIGATION
    # =================================================================
    add_heading(doc, "8. Site Navigation", level=1, color=AZ_MAGENTA)

    nav_items = [
        ("Top bar links", "Contact Us (https://www.astrazeneca.co.uk/contact-us.html) | AZ Employee Login (https://login.astrazeneca.com)"),
        ("Main navigation pages", "LUMINOS Data | Safety | Dosing & Administration | How TRELUXIA Works | Resources"),
        ("Utility", "Search | Login"),
    ]
    for label, val in nav_items:
        add_field_value(doc, label, val)

    doc.add_page_break()

    # =================================================================
    # 9. PAGE CONTENT
    # =================================================================
    add_heading(doc, "9. Page Content", level=1, color=AZ_MAGENTA)

    notice = doc.add_paragraph()
    run = notice.add_run(
        "IMPORTANT: All copy below is final and MLR-approved. It must be used exactly as written \u2014 "
        "do not modify, rephrase, or abbreviate any text. All superscript reference numbers, statistical "
        "values, and regulatory language must be reproduced verbatim."
    )
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RED_NOTICE

    notice2 = doc.add_paragraph()
    run = notice2.add_run(
        "Each page must end with expandable sections for Prescribing Information, Adverse Event Reporting, "
        "and References (see sections 5, 6, and 7 above)."
    )
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RED_NOTICE

    notice3 = doc.add_paragraph()
    run = notice3.add_run(
        'TRELUXIA brand rule: TRELUXIA always appears in capitals, with \u2122 on first mention per page. '
        'Generic name (trelimovab) in lowercase parentheses on first mention. '
        'Tagline "Breathe beyond limits." verbatim only.'
    )
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RED_NOTICE

    add_separator(doc)

    # =====================================================================
    # PAGE 1: HOME
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 1: Home", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/treluxia/")
    add_separator(doc)

    # Section 1 — Hero
    add_heading(doc, "Section 1 \u2014 Hero (full-width image with text overlay)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "hero-teaser")
    doc.add_paragraph()
    add_image_with_caption(doc, "hero-home.jpeg", width=Inches(5.5))

    add_field_value(doc, "Heading", "TRELUXIA\u2122 (trelimovab)")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Broad anti-inflammatory control for adults and adolescents with severe uncontrolled asthma, "
        "irrespective of inflammatory phenotype. Breathe beyond limits.\u00b9"
    )
    add_field_value(doc, "Call to action", "Explore the LUMINOS data \u2192 /treluxia/luminos-data")

    add_separator(doc)

    # Section 2 — Key benefit cards
    add_heading(doc, "Section 2 \u2014 Three key benefit cards (equal columns)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "cards-teaser")

    # Card 1 — Exacerbations
    doc.add_paragraph()
    add_image_with_caption(doc, "card-exacerbations.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "56% reduction in asthma exacerbations")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "In LUMINOS-1, TRELUXIA reduced the annualised asthma exacerbation rate by 56% versus placebo "
        "across the overall severe asthma population, irrespective of baseline eosinophil count or "
        "inflammatory phenotype (rate ratio 0.44; P<0.001).\u00b9"
    )
    add_field_value(doc, "Card link", "View LUMINOS data \u2192 /treluxia/luminos-data")

    add_separator(doc)

    # Card 2 — Lung function
    add_image_with_caption(doc, "card-lung-function.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Clinically meaningful lung function improvement")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "TRELUXIA improved pre-bronchodilator FEV\u2081 by 0.25 L compared with placebo at Week 52 "
        "(P<0.001), demonstrating sustained and clinically meaningful improvement in airflow limitation "
        "alongside exacerbation reduction.\u00b9"
    )
    add_field_value(doc, "Card link", "Explore lung function data \u2192 /treluxia/luminos-data")

    add_separator(doc)

    # Card 3 — OCS sparing
    add_image_with_caption(doc, "card-ocs.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Enabling oral corticosteroid reduction")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "In LUMINOS-OCS, 71.4% of patients achieved \u226550% reduction in their maintenance oral corticosteroid "
        "dose with TRELUXIA, and 37.9% eliminated OCS completely while maintaining asthma control "
        "(P<0.001 for both).\u00b2"
    )
    add_field_value(doc, "Card link", "View OCS-sparing data \u2192 /treluxia/luminos-data")

    add_separator(doc)

    # Section 3 — Disease context
    add_heading(doc, "Section 3 \u2014 Disease context (centred text) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "Severe asthma: an unmet need beyond type 2 inflammation")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Approximately 5\u201310% of adults with asthma have severe disease that remains uncontrolled despite "
        "optimised inhaler therapy.\u2074 While existing biologics target specific type 2 inflammatory pathways, "
        "a significant proportion of patients with severe asthma do not have an elevated type 2 biomarker "
        "signature, or have mixed inflammatory phenotypes that respond incompletely to single-pathway "
        "inhibition. TSLP acts upstream of both type 2 and non-type 2 inflammatory cascades, representing "
        "a broader therapeutic target.\u2075"
    )

    add_separator(doc)

    # Section 4 — Mechanism teaser
    add_heading(doc, "Section 4 \u2014 Mechanism teaser (two-column: image left, text right) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-moa-preview.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Targeting TSLP: upstream control of airway inflammation")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "TSLP is an epithelial-derived cytokine released at the top of the asthma inflammatory cascade. "
        "By blocking TSLP, TRELUXIA inhibits multiple downstream pathways driving both eosinophilic and "
        "non-eosinophilic inflammation, providing broad anti-inflammatory control regardless of phenotype.\u00b3 \u2075"
    )
    add_field_value(doc, "Call to action", "Explore how TRELUXIA works \u2192 /treluxia/how-treluxia-works")

    add_separator(doc)

    # Section 5 — Accordion
    add_heading(doc, "Section 5 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "accordion")
    add_body(doc, "Expandable sections for: Prescribing Information | Adverse Event Reporting | References (Use approved text from sections 5, 6, and 7 above)", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: TRELUXIA (trelimovab) | Severe Asthma Treatment | AstraZeneca UK")
    add_body(doc, "Description: TRELUXIA (trelimovab) is a human anti-TSLP monoclonal antibody for adults and adolescents with severe uncontrolled asthma. Explore LUMINOS clinical data, safety, and dosing for UK healthcare professionals.")

    # =====================================================================
    # PAGE 2: LUMINOS DATA
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 2: LUMINOS Data", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/treluxia/luminos-data")
    add_separator(doc)

    # Hero
    add_heading(doc, "Section 1 \u2014 Hero (full-width image with text overlay)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "hero-teaser")
    doc.add_paragraph()
    add_image_with_caption(doc, "hero-efficacy.jpeg", width=Inches(5.5))

    add_field_value(doc, "Heading", "The LUMINOS clinical programme")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "TRELUXIA\u2122 (trelimovab) demonstrated significant exacerbation reduction, lung function improvement, "
        "and oral corticosteroid sparing across the full spectrum of severe asthma in two Phase III trials.\u00b9 \u00b2"
    )

    add_separator(doc)

    # Programme overview
    add_heading(doc, "Section 2 \u2014 Programme overview (centred text) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "Broad efficacy across severe asthma phenotypes")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "The LUMINOS programme evaluated trelimovab in two distinct severe asthma populations: "
        "LUMINOS-1 assessed exacerbation reduction and lung function in 1,061 adults and adolescents with "
        "uncontrolled severe asthma across all inflammatory phenotypes. LUMINOS-OCS assessed oral "
        "corticosteroid sparing in 407 adults with OCS-dependent severe asthma, demonstrating the potential "
        "to reduce the burden of chronic systemic corticosteroid use.\u00b9 \u00b2"
    )

    add_separator(doc)

    # Tabs
    add_heading(doc, "Section 3 \u2014 Clinical data (two tabs)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "tabs-large")

    # Tab 1 — LUMINOS-1
    doc.add_paragraph()
    add_body(doc, 'Tab 1: "LUMINOS-1: Exacerbation reduction"', bold=True)
    add_image_with_caption(doc, "tab-luminos1.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "LUMINOS-1: 56% reduction in asthma exacerbations across all phenotypes")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "In LUMINOS-1, a randomised, double-blind, placebo-controlled trial in 1,061 adults and adolescents "
        "with severe asthma on medium- or high-dose ICS plus additional controllers, TRELUXIA reduced the "
        "annualised asthma exacerbation rate by 56% versus placebo across the overall population "
        "(rate ratio 0.44; 95% CI: 0.37\u20130.53; P<0.001). The benefit was observed irrespective of baseline "
        "blood eosinophil count: 62% reduction in patients with eosinophils \u2265300 cells/\u03bcL (RR 0.38; P<0.001) "
        "and 41% reduction in patients with eosinophils <300 cells/\u03bcL (RR 0.59; P<0.001).\u00b9"
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Body text (continued): ")
    run.bold = True
    p.add_run(
        "TRELUXIA significantly improved pre-bronchodilator FEV\u2081 by 0.25 L at Week 52 versus placebo "
        "(P<0.001). Patients also reported clinically meaningful improvements in asthma symptom control "
        "(ACQ-6 difference: \u22120.48; P<0.001). Exacerbations requiring hospitalisation or emergency room "
        "visits were reduced by 77% (rate ratio 0.23; P<0.001).\u00b9"
    )

    add_body(doc, "Data table:", bold=True)
    add_table(doc,
        ["Endpoint", "TRELUXIA (n=529)", "Placebo (n=532)", "Treatment effect"],
        [
            ("AAER (overall)", "0.93", "2.10", "RR 0.44 (0.37\u20130.53); P<0.001"),
            ("AAER (eos \u2265300)", "0.85", "2.26", "RR 0.38 (0.29\u20130.49); P<0.001"),
            ("AAER (eos <300)", "1.14", "1.92", "RR 0.59 (0.45\u20130.78); P<0.001"),
            ("Pre-BD FEV\u2081 at Week 52", "+0.29 L", "+0.04 L", "+0.25 L (0.18\u20130.32); P<0.001"),
            ("ACQ-6 at Week 52", "\u22121.55", "\u22121.07", "\u22120.48 (\u22120.62 to \u22120.34); P<0.001"),
        ])

    add_separator(doc)

    # Tab 2 — LUMINOS-OCS
    add_body(doc, 'Tab 2: "LUMINOS-OCS: Oral corticosteroid sparing"', bold=True)
    add_image_with_caption(doc, "tab-luminos-ocs.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "LUMINOS-OCS: Enabling steroid freedom for OCS-dependent patients")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "LUMINOS-OCS was a randomised, double-blind, placebo-controlled trial in 407 adults with severe "
        "asthma dependent on maintenance oral corticosteroids (\u22655 mg prednisolone equivalent daily) "
        "receiving high-dose ICS plus additional controllers.\u00b2"
    )
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Body text (continued): ")
    run.bold = True
    p.add_run(
        "TRELUXIA enabled a median 75% reduction in OCS dose at Week 48, compared with 25% for placebo "
        "(odds ratio 2.58; P<0.001). Over one-third of TRELUXIA-treated patients (37.9%) achieved complete "
        "OCS elimination, compared with 10.8% of placebo patients (OR 5.07; P<0.001). Critically, OCS "
        "reduction was achieved while maintaining asthma control: the AAER during the OCS reduction phase "
        "was 61% lower with TRELUXIA than placebo (RR 0.39; P<0.001), and ACQ-6 scores improved "
        "significantly (difference: \u22120.73; P<0.001).\u00b2"
    )

    add_body(doc, "Data table:", bold=True)
    add_table(doc,
        ["Endpoint", "TRELUXIA (n=203)", "Placebo (n=204)", "Treatment effect"],
        [
            ("Median OCS reduction at Week 48", "\u221275%", "\u221225%", "OR 2.58 (1.79\u20133.72); P<0.001"),
            ("\u226550% OCS reduction", "71.4%", "41.7%", "OR 3.49 (2.31\u20135.27); P<0.001"),
            ("Complete OCS elimination", "37.9%", "10.8%", "OR 5.07 (3.03\u20138.49); P<0.001"),
            ("AAER during OCS reduction", "0.76", "1.97", "RR 0.39 (0.28\u20130.53); P<0.001"),
            ("ACQ-6 at Week 48", "\u22121.41", "\u22120.68", "\u22120.73 (\u22120.97 to \u22120.49); P<0.001"),
        ])

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 4 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: LUMINOS Data | TRELUXIA (trelimovab) | Exacerbation & OCS Outcomes | AstraZeneca UK")
    add_body(doc, "Description: Explore the LUMINOS clinical programme for TRELUXIA (trelimovab) \u2014 Phase III exacerbation reduction, lung function improvement, and oral corticosteroid sparing in adults and adolescents with severe asthma.")

    # =====================================================================
    # PAGE 3: SAFETY
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 3: Safety", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/treluxia/safety")
    add_separator(doc)

    # Title block
    add_heading(doc, "Section 1 \u2014 Page header (text only, no image)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "title")
    add_field_value(doc, "Heading", "Safety profile of TRELUXIA")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "TRELUXIA\u2122 (trelimovab) has been evaluated in over 700 patients across the LUMINOS clinical "
        "programme, with treatment durations of up to 52 weeks.\u00b9 \u00b2 \u00b3"
    )

    add_separator(doc)

    # Key safety message
    add_heading(doc, "Section 2 \u2014 Key safety message (centred text) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "A favourable safety profile consistent with a targeted biologic")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "The overall safety profile of TRELUXIA is consistent with expectations for a human IgG2 "
        "monoclonal antibody targeting an epithelial cytokine. Serious adverse events were lower with "
        "TRELUXIA than placebo (8.4% vs 11.2%), driven by fewer asthma-related hospitalisations. Treatment "
        "discontinuation due to adverse events was low (2.4% vs 3.1%). The most common adverse events were "
        "mild upper respiratory tract infections and injection site reactions.\u00b9 \u00b2 \u00b3"
    )

    add_separator(doc)

    # Safety overview
    add_heading(doc, "Section 3 \u2014 Safety overview (centred text) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "introduction")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_field_value(doc, "Heading", "Safety profile across the LUMINOS programme")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Across pooled LUMINOS data (N=732 TRELUXIA), the adverse event profile was dominated by common "
        "respiratory infections and mild injection site reactions. No clinically significant immunosuppression, "
        "malignancy signal, or cardiovascular safety concerns were identified. Anti-drug antibodies were "
        "detected in 5.1% of patients but had no impact on efficacy or safety. Anaphylaxis was rare (0.4%) "
        "and all events resolved with standard management.\u00b9 \u00b2 \u00b3"
    )

    add_separator(doc)

    # AE table
    add_heading(doc, "Section 4 \u2014 Adverse events table | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "table-data")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    add_table(doc,
        ["Adverse event", "TRELUXIA (%)", "Placebo (%)"],
        [
            ("Nasopharyngitis", "10.4", "9.8"),
            ("Upper respiratory tract infection", "8.1", "7.4"),
            ("Headache", "6.7", "5.2"),
            ("Injection site reactions", "4.6", "2.8"),
            ("Arthralgia", "3.8", "3.1"),
            ("Back pain", "3.2", "2.6"),
            ("Pharyngitis", "2.9", "2.5"),
            ("Fatigue", "2.4", "1.9"),
        ])

    add_separator(doc)

    # Safety cards
    add_heading(doc, "Section 5 \u2014 Key safety consideration cards (equal columns)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "cards-teaser")

    # Card 1 — ISR
    doc.add_paragraph()
    add_image_with_caption(doc, "card-isr.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Injection site reactions")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Injection site reactions occurred in 4.6% of TRELUXIA-treated patients vs 2.8% with placebo. "
        "The most common were erythema, pain, and swelling. All ISRs were mild to moderate in severity. "
        "No injection site reaction led to treatment discontinuation.\u00b3"
    )

    add_separator(doc)

    # Card 2 — Anaphylaxis
    add_image_with_caption(doc, "card-anaphylaxis.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Anaphylaxis and hypersensitivity")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Anaphylaxis was reported in 3 patients (0.4%) receiving TRELUXIA. All events occurred within "
        "24 hours of injection and resolved with standard treatment. The first 3 doses should be "
        "administered under healthcare professional supervision. Patients should carry an adrenaline "
        "auto-injector for the duration of treatment.\u00b3"
    )

    add_separator(doc)

    # Card 3 — Infections
    add_image_with_caption(doc, "card-infections.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Infections and immunogenicity")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Upper respiratory tract infections were the most common adverse events, occurring at similar "
        "rates in TRELUXIA and placebo groups. No clinically significant immunosuppression was observed. "
        "Anti-drug antibodies were detected in 5.1% but had no impact on efficacy, safety, or pharmacokinetics.\u00b9 \u00b3"
    )

    add_separator(doc)

    # Special populations
    add_heading(doc, "Section 6 \u2014 Special populations (two-column: image left, text right) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-special-pops.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Special populations")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Adolescents (12\u201317 years): Same dose as adults (210 mg Q4W). In LUMINOS-1, 63 adolescents "
        "received TRELUXIA with consistent efficacy and safety.\u00b3\n\n"
        "Elderly patients: No dose adjustment required in patients aged \u226565 years. 11% of LUMINOS-1 "
        "patients were \u226565 years.\u00b3\n\n"
        "Pregnancy and fertility: TRELUXIA should only be used during pregnancy if the potential benefit "
        "justifies the potential risk to the foetus. Human IgG antibodies cross the placental barrier.\u00b3\n\n"
        "Renal/hepatic impairment: No dose adjustment for mild to moderate impairment. Not studied in "
        "severe impairment.\u00b3"
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 7 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: Safety | TRELUXIA (trelimovab) | Adverse Events & Monitoring | AstraZeneca UK")
    add_body(doc, "Description: Review the safety profile of TRELUXIA (trelimovab) including injection site reactions, anaphylaxis risk, infection rates, and special population recommendations for severe asthma.")

    # =====================================================================
    # PAGE 4: DOSING & ADMINISTRATION
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 4: Dosing & Administration", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/treluxia/dosing")
    add_separator(doc)

    # Hero
    add_heading(doc, "Section 1 \u2014 Hero (full-width image with text overlay)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "hero-teaser")
    doc.add_paragraph()
    add_image_with_caption(doc, "hero-dosing.jpeg", width=Inches(5.5))

    add_field_value(doc, "Heading", "Dosing and administration")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "TRELUXIA\u2122 (trelimovab) offers a simple once-every-4-weeks subcutaneous injection for adults "
        "and adolescents with severe asthma, with the option for self-administration after initial "
        "supervised doses.\u00b3"
    )

    add_separator(doc)

    # Dosing regimen
    add_heading(doc, "Section 2 \u2014 Dosing regimen (two-column) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-dosing.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Simple dosing with no titration required")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Dose: 210 mg subcutaneous injection once every 4 weeks (Q4W).\u00b3\n\n"
        "No weight-based dosing adjustment required.\u00b3\n\n"
        "No dose titration required \u2014 full therapeutic dose from Day 1.\u00b3\n\n"
        "Same dose for adults and adolescents aged \u226512 years.\u00b3\n\n"
        "Available as a pre-filled syringe or pre-filled pen (autoinjector) for patient convenience.\u00b3"
    )

    add_separator(doc)

    # Administration
    add_heading(doc, "Section 3 \u2014 Administration guidance (two-column)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-admin.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Administration and self-injection guidance")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "The first 3 doses should be administered under the supervision of a healthcare professional. "
        "Thereafter, patients or caregivers may self-administer after training in subcutaneous injection "
        "technique.\u00b3\n\n"
        "Injection sites: Thigh, abdomen (excluding 5 cm around the navel), or upper arm (if administered "
        "by caregiver). Rotate injection sites between doses.\u00b3\n\n"
        "Allow TRELUXIA to reach room temperature (approximately 30 minutes) before injection. Do not use "
        "external heat sources. Do not shake.\u00b3\n\n"
        "Do not inject into areas that are tender, bruised, erythematous, or indurated.\u00b3"
    )

    add_separator(doc)

    # Concomitant therapy
    add_heading(doc, "Section 4 \u2014 Concomitant therapy and corticosteroid management (two-column) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-ocs-management.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Concomitant therapy and corticosteroid management")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "TRELUXIA should be added to existing maintenance asthma therapy. Do not abruptly discontinue "
        "inhaled corticosteroids or oral corticosteroids upon initiation.\u00b3\n\n"
        "For patients receiving maintenance oral corticosteroids, reduction may be considered after at "
        "least 12 weeks of TRELUXIA treatment, under physician supervision. Reduce OCS dose gradually "
        "(no faster than 2.5 mg prednisolone equivalent per month) while monitoring asthma symptoms and "
        "exacerbation frequency.\u00b2 \u00b3\n\n"
        "TRELUXIA may be used alongside ICS, LABA, LTRA, LAMA, theophylline, and oral corticosteroids. "
        "No clinically significant drug interactions have been identified.\u00b3"
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 5 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: Dosing | TRELUXIA (trelimovab) | Q4W Subcutaneous Injection | AstraZeneca UK")
    add_body(doc, "Description: Dosing and administration guidance for TRELUXIA (trelimovab) including injection technique, self-administration training, concomitant therapy, and corticosteroid management in severe asthma.")

    # =====================================================================
    # PAGE 5: HOW TRELUXIA WORKS
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 5: How TRELUXIA Works", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/treluxia/how-treluxia-works")
    add_separator(doc)

    # Hero
    add_heading(doc, "Section 1 \u2014 Hero (full-width image with text overlay)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "hero-teaser")
    doc.add_paragraph()
    add_image_with_caption(doc, "hero-moa.jpeg", width=Inches(5.5))

    add_field_value(doc, "Heading", "Upstream control at the source of airway inflammation")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "TRELUXIA\u2122 (trelimovab) blocks TSLP, an epithelial cytokine that initiates multiple inflammatory "
        "cascades in asthma \u2014 providing broad anti-inflammatory control beyond single-pathway biologics.\u00b3 \u2075"
    )

    add_separator(doc)

    # TSLP pathway
    add_heading(doc, "Section 2 \u2014 The TSLP pathway (two-column)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-tslp-pathway.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "TSLP: the upstream driver of severe asthma inflammation")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Thymic stromal lymphopoietin (TSLP) is produced by airway epithelial cells in response to "
        "environmental triggers including allergens, viral infections, pollutants, and mechanical injury.\u2075\n\n"
        "Once released, TSLP activates dendritic cells and innate lymphoid cells (ILC2s), initiating a "
        "cascade of downstream inflammatory events: Th2 cell differentiation and IL-4/IL-5/IL-13 production, "
        "eosinophil recruitment and activation, IgE class switching and mast cell sensitisation, and "
        "structural cell activation driving airway remodelling.\u2074 \u2075\n\n"
        "Crucially, TSLP also drives non-type 2 inflammatory pathways including mast cell cytokine release "
        "and neutrophil-mediated inflammation, making it relevant across the full phenotypic spectrum of "
        "severe asthma.\u2075"
    )

    add_separator(doc)

    # TRELUXIA mechanism
    add_heading(doc, "Section 3 \u2014 TRELUXIA mechanism (two-column) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-mechanism.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "How TRELUXIA blocks TSLP signalling")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Trelimovab is a human IgG2\u03bb monoclonal antibody that binds specifically to TSLP, preventing its "
        "interaction with the heterodimeric TSLP receptor complex (TSLPR/IL-7R\u03b1) on the surface of immune "
        "cells.\u00b3\n\n"
        "By neutralising TSLP at the top of the inflammatory cascade, trelimovab inhibits the activation "
        "of downstream type 2 and non-type 2 pathways simultaneously \u2014 reducing eosinophilic inflammation, "
        "Th2 cytokine production, IgE synthesis, mast cell activation, and non-eosinophilic inflammatory "
        "mechanisms.\u00b3 \u2075\n\n"
        "This broad upstream mechanism distinguishes TRELUXIA from biologics that target single downstream "
        "mediators (IL-5, IL-4/IL-13, IgE), enabling efficacy across all severe asthma phenotypes including "
        "those with low eosinophil counts and mixed inflammatory signatures.\u00b3"
    )

    add_separator(doc)

    # Treatment positioning
    add_heading(doc, "Section 4 \u2014 Positioning in the treatment pathway (two-column) | light background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: light").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-positioning.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "TRELUXIA in the severe asthma treatment pathway")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "Current guidelines recommend biologic therapy for patients with severe asthma that remains "
        "uncontrolled despite high-dose ICS plus additional controllers.\u2074 Existing biologic options \u2014 "
        "anti-IL-5/5R, anti-IL-4/13, and anti-IgE \u2014 primarily target type 2 inflammatory pathways and "
        "require biomarker-based patient selection.\u2074\n\n"
        "TRELUXIA\u2019s upstream TSLP blockade offers a complementary approach: it is indicated irrespective "
        "of inflammatory phenotype, providing a treatment option for patients across the entire severe "
        "asthma spectrum \u2014 including those who may not be eligible for or who have responded inadequately "
        "to existing biologics targeting single downstream pathways.\u00b3 \u2074"
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 5 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: How TRELUXIA Works | Anti-TSLP Mechanism | Upstream Asthma Control | AstraZeneca UK")
    add_body(doc, "Description: Understand the mechanism of action of TRELUXIA (trelimovab) \u2014 an anti-TSLP monoclonal antibody providing broad upstream control of airway inflammation in severe asthma.")

    # =====================================================================
    # PAGE 6: RESOURCES
    # =====================================================================
    doc.add_page_break()
    add_heading(doc, "PAGE 6: Resources", level=2, color=AZ_MAGENTA)
    add_field_value(doc, "URL path", "/treluxia/resources")
    add_separator(doc)

    # Title
    add_heading(doc, "Section 1 \u2014 Page header (text only, no image)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "title")
    add_field_value(doc, "Heading", "Resources for healthcare professionals")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "TRELUXIA\u2122 (trelimovab) resources to support clinical decision-making and patient care "
        "in severe asthma."
    )

    add_separator(doc)

    # Resource cards
    add_heading(doc, "Section 2 \u2014 Resource cards (equal columns)", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "cards-teaser")

    # Card 1
    doc.add_paragraph()
    add_image_with_caption(doc, "card-prescribing-guide.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Prescribing guide")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Download the TRELUXIA prescribing guide with dosing summary, injection technique checklist, "
        "monitoring recommendations, and concomitant therapy guidance for severe asthma in adults and "
        "adolescents."
    )
    add_field_value(doc, "Card link", "Download prescribing guide (PDF)")

    add_separator(doc)

    # Card 2
    add_image_with_caption(doc, "card-patient-materials.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "Patient support materials")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Access patient-facing materials including the TRELUXIA self-injection guide, asthma action plan "
        "template, and OCS reduction diary to support shared decision-making and self-management."
    )
    add_field_value(doc, "Card link", "View patient materials")

    add_separator(doc)

    # Card 3
    add_image_with_caption(doc, "card-clinical-data.jpeg", width=Inches(3))
    add_field_value(doc, "Card heading", "LUMINOS clinical data summary")
    p = doc.add_paragraph()
    run = p.add_run("Card body: ")
    run.bold = True
    p.add_run(
        "Request the LUMINOS clinical data compendium with full trial results from LUMINOS-1 and "
        "LUMINOS-OCS, including subgroup analyses by eosinophil count, atopic status, and prior biologic use."
    )
    add_field_value(doc, "Card link", "Request clinical data pack")

    add_separator(doc)

    # Contact
    add_heading(doc, "Section 3 \u2014 Medical information contact (two-column) | highlight background", level=3, color=BRAND_COLOUR)
    add_field_value(doc, "Block", "columns-teaser")
    p = doc.add_paragraph()
    run = p.add_run("Section metadata: ")
    run.bold = True
    p.add_run("Style: highlight").font.color.rgb = GREY_TEXT

    doc.add_paragraph()
    add_image_with_caption(doc, "columns-contact.jpeg", width=Inches(3.5))

    add_field_value(doc, "Heading", "Medical information and support")
    p = doc.add_paragraph()
    run = p.add_run("Body text: ")
    run.bold = True
    p.add_run(
        "For medical information enquiries about TRELUXIA, contact AstraZeneca Medical Information:\n\n"
        "Online: contactazmedical.astrazeneca.com\n"
        "Phone: 0800 783 0033\n"
        "Email: medinfo.uk@astrazeneca.com\n\n"
        "For adverse event reporting, visit www.mhra.gov.uk/yellowcard or contact AstraZeneca directly."
    )

    add_separator(doc)

    # Accordion + metadata
    add_heading(doc, "Section 4 \u2014 Prescribing information footer", level=3, color=BRAND_COLOUR)
    add_body(doc, "Block: accordion  |  Expandable: PI | AE Reporting | References", italic=True)

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("Page metadata")
    run.bold = True
    run.font.color.rgb = AZ_MAGENTA
    add_body(doc, "Title: Resources | TRELUXIA (trelimovab) | HCP Support Materials | AstraZeneca UK")
    add_body(doc, "Description: Download prescribing guides, patient support materials, and clinical data summaries for TRELUXIA (trelimovab) in severe asthma. Contact AstraZeneca Medical Information for enquiries.")

    # =================================================================
    # 10. FOOTER CONTENT
    # =================================================================
    doc.add_page_break()
    add_heading(doc, "10. Footer Content", level=1, color=AZ_MAGENTA)

    footer_rows = [
        ("Row 1 \u2014 Brand",
         "AstraZeneca logo | GB-98204 | DOP: March 2026 | \u00a9 AstraZeneca 2026. TRELUXIA is a trademark of the AstraZeneca group of companies."),
        ("Row 2 \u2014 Site links",
         "LUMINOS Data | Safety | Dosing & Administration | How TRELUXIA Works | Resources"),
        ("Row 3 \u2014 Regulatory links",
         "Report Adverse Event (https://yellowcard.mhra.gov.uk/) | "
         "Medical Information (https://contactazmedical.astrazeneca.com/) | "
         "Privacy Policy (https://www.astrazeneca.co.uk/our-company/privacy-notice.html) | "
         "Terms of Use (https://www.astrazeneca.co.uk/our-company/terms-of-use.html) | "
         "Accessibility (https://www.astrazeneca.co.uk/accessibility.html)"),
        ("Row 4 \u2014 Date", "Date of Preparation: March 2026"),
    ]
    for label, val in footer_rows:
        add_field_value(doc, label, val)

    add_separator(doc)

    # =================================================================
    # 11. IMAGE ASSETS
    # =================================================================
    add_heading(doc, "11. Image Assets", level=1, color=AZ_MAGENTA)

    add_body(doc, (
        f"All images are generated using the AZ brand image pipeline and deployed to {CDN_BASE}/. "
        "Each image is shown below with its CDN URL and usage context."
    ))

    doc.add_paragraph()

    asset_headers = ["#", "Filename", "CDN URL", "Dimensions", "Usage"]
    asset_rows = []
    for idx, (filename, usage) in enumerate(IMAGE_MANIFEST.items(), 1):
        dims = "1440\u00d7810" if "hero" in filename else "800\u00d7600"
        asset_rows.append((str(idx), filename, f"{CDN_BASE}/{filename}", dims, usage))

    add_table(doc, asset_headers, asset_rows)

    # Add image previews
    doc.add_paragraph()
    add_heading(doc, "Image previews", level=2, color=AZ_MAGENTA)

    for filename, usage in IMAGE_MANIFEST.items():
        is_hero = "hero" in filename
        width = Inches(5.0) if is_hero else Inches(3.0)
        add_image_with_caption(doc, filename, width=width)
        doc.add_paragraph()

    return doc


# =====================================================================
# ENTRY POINT
# =====================================================================

if __name__ == "__main__":
    print(f"Generating TRELUXIA website briefing DOCX...")
    print(f"Image source: {IMG_DIR}")
    print(f"Output: {OUTPUT_PATH}")
    print()

    if os.path.isdir(IMG_DIR):
        imgs = [f for f in os.listdir(IMG_DIR) if f.endswith(('.jpeg', '.jpg', '.png'))]
        print(f"Found {len(imgs)} images in {IMG_DIR}")
    else:
        print(f"WARNING: Image directory not found at {IMG_DIR}")
        print("Images will show as placeholders in the DOCX.")

    print()
    print("Building document...")

    doc = build_document()

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    doc.save(OUTPUT_PATH)

    print()
    print(f"Done! Saved to: {OUTPUT_PATH}")
    print(f"File size: {os.path.getsize(OUTPUT_PATH) / 1024:.0f} KB")
